// ─── COMPANY CONFIG ────────────────────────────────────────────────────────
// Single source of truth for Excel row mappings per company + sheet.
// Budget cols: N–Y (0-based index 13–24), Actual cols: AC–AN (28–39)

export const BUDGET_COLS = [13,14,15,16,17,18,19,20,21,22,23,24];
export const ACTUAL_COLS = [28,29,30,31,32,33,34,35,36,37,38,39];
export const MONTH_LABELS = ["Oca","Şub","Mar","Nis","May","Haz","Tem","Ağu","Eyl","Eki","Kas","Ara"];

export interface RowConfig {
  row: number;       // 1-based Excel row
  label: string;
  unit?: string;
}

export interface DeptConfig {
  code: string;
  row: number;
  label: string;
  /** If true, monthly totals are computed from item sums (no physical subtotal row). */
  virtual?: boolean;
  itemRows?: RowConfig[];
  /** Paired rows for TL + Litre items (e.g. arac_yakit vehicles): [tlRow, litreRow] */
  itemPairs?: [number, number][];
}

export interface ParamConfig {
  code: string;
  row: number;
  label: string;
  unit: string;
  noRound?: boolean; // true for decimal ratio/percentage params (prevents Math.round mangling)
  deptCode?: string; // optional: groups param under a specific dept in the UI
}

export interface CategoryConfig {
  total: RowConfig;
  depts: DeptConfig[];
  params: ParamConfig[];
}

export interface SheetConfig {
  sheet: string;
  categories: Record<string, CategoryConfig>;
}

export const COMPANY_CONFIG: Record<string, SheetConfig> = {
  "2410": {
    sheet: "Model Gider",
    categories: {
      guvenlik: {
        total: { row: 20, label: "Güvenlik Giderleri", unit: "TL Karşılığı" },
        depts: [
          {
            code: "gyg", row: 72, label: "GYG",
            itemRows: [
              { row: 73, label: "Proje Müdürü", unit: "TL" },
              { row: 74, label: "Vardiya Amiri", unit: "TL" },
              { row: 75, label: "Nizamiye", unit: "TL" },
              { row: 76, label: "Helikopter Pisti Nizamiye", unit: "TL" },
              { row: 77, label: "Hyundai", unit: "TL" },
              { row: 78, label: "PMO Bina (Resepsiyonist)", unit: "TL" },
              { row: 79, label: "U-Turn Kuzey", unit: "TL" },
              { row: 80, label: "U-Turn Güney", unit: "TL" },
              { row: 81, label: "CCTV", unit: "TL" },
              { row: 82, label: "Araç Devriye", unit: "TL" },
            ],
          },
          {
            code: "oht", row: 84, label: "OHT",
            itemRows: [
              { row: 85, label: "OHT 1A Fenertepe", unit: "TL" },
              { row: 86, label: "OHT 1B Fenertepe", unit: "TL" },
              { row: 87, label: "OHT Başakşehir Opet", unit: "TL" },
              { row: 88, label: "OHT 2 Küçük Shell", unit: "TL" },
              { row: 89, label: "OHT 3 Çiftalân", unit: "TL" },
              { row: 90, label: "OHT Çekmeköy Opet B", unit: "TL" },
              { row: 91, label: "OHT Çekmeköy Opet A", unit: "TL" },
              { row: 92, label: "OHT Poyraz Opet A", unit: "TL" },
              { row: 93, label: "OHT Poyraz Opet B", unit: "TL" },
              { row: 94, label: "OHT 4 Reşadiye", unit: "TL" },
              { row: 95, label: "OHT 5 Ömerli", unit: "TL" },
            ],
          },
          {
            code: "ictas", row: 97, label: "İçtaş Güvenlik",
            itemRows: [
              { row: 98,  label: "Nizamiye Grubu 1", unit: "TL" },
              { row: 99,  label: "Güvenlik Grubu 1", unit: "TL" },
              { row: 100, label: "Nizamiye Grubu 2", unit: "TL" },
              { row: 101, label: "Güvenlik Grubu 2", unit: "TL" },
            ],
          },
          {
            code: "operasyon", row: 111, label: "Operasyon",
            itemRows: [
              { row: 112, label: "Bakım İşletme Odayeri", unit: "TL" },
              { row: 113, label: "Bakım İşletme Hüseynili", unit: "TL" },
              { row: 114, label: "G8 Araçlı Devriye", unit: "TL" },
              { row: 115, label: "Trafo Devriye Başakşehir", unit: "TL" },
              { row: 116, label: "Gişe-3 Ağaçlı", unit: "TL" },
              { row: 117, label: "Avrupa Kimyasal Tır Parkı", unit: "TL" },
              { row: 118, label: "Asya Kimyasal Tır Parkı", unit: "TL" },
              { row: 120, label: "Ek Giderler (araç+yakıt+amort.)", unit: "TL" },
            ],
          },
          {
            code: "kilyos", row: 123, label: "Kilyos",
            itemRows: [], // tek satır, endeks bağlı
          },
        ],
        params: [
          { code: "ucret_proje_muduru",  row: 21, label: "Proje Müdürü Ücret",       unit: "TL" },
          { code: "ucret_vardiya_amiri", row: 22, label: "Vardiya Amiri Ücret",      unit: "TL" },
          { code: "ucret_guvenlik",      row: 23, label: "Güvenlik Personeli Ücret", unit: "TL" },
          { code: "ucret_kandilli",      row: 24, label: "Proje (Kandilli) Ücret",   unit: "TL" },
          { code: "kisi_toplam",         row: 25, label: "Kişi Sayısı Toplam",       unit: "Kişi" },
          { code: "kisi_gyg",            row: 26, label: "GYG Kişi",                 unit: "Kişi" },
          { code: "kisi_gyg_proje",      row: 27, label: "Proje Müdürü Kişi",        unit: "Kişi" },
          { code: "kisi_gyg_vardiya",    row: 28, label: "Vardiya Amiri Kişi",       unit: "Kişi" },
          { code: "kisi_gyg_nizamiye",   row: 29, label: "Nizamiye Kişi",            unit: "Kişi" },
          { code: "kisi_gyg_heli",       row: 30, label: "Helikopter Pisti Kişi",    unit: "Kişi" },
          { code: "kisi_gyg_hyundai",    row: 31, label: "Hyundai Kişi",             unit: "Kişi" },
          { code: "kisi_gyg_pmo",        row: 32, label: "PMO Bina Kişi",            unit: "Kişi" },
          { code: "kisi_gyg_uturn_k",    row: 33, label: "U-Turn Kuzey Kişi",        unit: "Kişi" },
          { code: "kisi_gyg_uturn_g",    row: 34, label: "U-Turn Güney Kişi",        unit: "Kişi" },
          { code: "kisi_gyg_cctv",       row: 35, label: "CCTV Kişi",                unit: "Kişi" },
          { code: "kisi_gyg_arac",       row: 36, label: "Araç Devriye Kişi",        unit: "Kişi" },
          { code: "kisi_oht",            row: 37, label: "OHT Kişi",                 unit: "Kişi" },
          { code: "kisi_oht_1a",         row: 38, label: "OHT 1A Fenertepe Kişi",   unit: "Kişi" },
          { code: "kisi_oht_1b",         row: 39, label: "OHT 1B Fenertepe Kişi",   unit: "Kişi" },
          { code: "kisi_oht_bsk",        row: 40, label: "OHT Başakşehir Kişi",      unit: "Kişi" },
          { code: "kisi_oht_shell",      row: 41, label: "OHT Küçük Shell Kişi",     unit: "Kişi" },
          { code: "kisi_oht_cifta",      row: 42, label: "OHT Çiftalân Kişi",        unit: "Kişi" },
          { code: "kisi_oht_cek_b",      row: 43, label: "OHT Çekmeköy B Kişi",      unit: "Kişi" },
          { code: "kisi_oht_cek_a",      row: 44, label: "OHT Çekmeköy A Kişi",      unit: "Kişi" },
          { code: "kisi_oht_poy_a",      row: 45, label: "OHT Poyraz A Kişi",        unit: "Kişi" },
          { code: "kisi_oht_poy_b",      row: 46, label: "OHT Poyraz B Kişi",        unit: "Kişi" },
          { code: "kisi_oht_res",        row: 47, label: "OHT Reşadiye Kişi",         unit: "Kişi" },
          { code: "kisi_oht_omerli",     row: 48, label: "OHT Ömerli Kişi",           unit: "Kişi" },
          { code: "kisi_operasyon",      row: 62, label: "Operasyon Kişi",            unit: "Kişi" },
          { code: "kisi_ops_odayeri",    row: 63, label: "Bakım Odayeri Kişi",        unit: "Kişi" },
          { code: "kisi_ops_huseynili",  row: 64, label: "Bakım Hüseynili Kişi",      unit: "Kişi" },
          { code: "kisi_ops_g8",         row: 65, label: "G8 Devriye Kişi",           unit: "Kişi" },
          { code: "kisi_ops_trafo",      row: 66, label: "Trafo Devriye Kişi",        unit: "Kişi" },
          { code: "kisi_ops_gise",       row: 67, label: "Gişe-3 Kişi",               unit: "Kişi" },
          { code: "kisi_ops_avrupa",     row: 68, label: "Avrupa Tır Parkı Kişi",     unit: "Kişi" },
          { code: "kisi_ops_asya",       row: 69, label: "Asya Tır Parkı Kişi",       unit: "Kişi" },
        ],
      },
      temizlik: {
        total: { row: 124, label: "Temizlik Giderleri", unit: "TL Karşılığı" },
        depts: [
          {
            code: "gyg", row: 149, label: "GYG",
            itemRows: [
              { row: 150, label: "AKM Binası", unit: "TL" },
              { row: 151, label: "PMO Binası + VIP Ofis", unit: "TL" },
            ],
          },
          {
            code: "ictas", row: 153, label: "İçtaş",
            itemRows: [
              { row: 154, label: "İçtaş Temizlik", unit: "TL" },
            ],
          },
          {
            code: "kamu", row: 156, label: "Kamu",
            itemRows: [
              { row: 157, label: "Köprü Koruma Amirliği", unit: "TL" },
              { row: 158, label: "KGM Binası", unit: "TL" },
            ],
          },
          {
            code: "oht", row: 160, label: "OHT",
            itemRows: [
              { row: 161, label: "OHT", unit: "TL" },
              { row: 162, label: "OHT Ekip Sorumlusu", unit: "TL" },
              { row: 163, label: "OHT Mesai Giderleri", unit: "TL" },
              { row: 164, label: "OHT Ek Giderler (araç+yakıt)", unit: "TL" },
            ],
            // Note: rows 167-168 are negative allocation rows (-441,884 / -462,000)
            // These are included in OHT total (row 160) already, skip as items
          },
          {
            code: "operasyon", row: 169, label: "Operasyon",
            itemRows: [
              { row: 170, label: "Bahçıvan", unit: "TL" },
              { row: 171, label: "AKM Çevre", unit: "TL" },
              { row: 172, label: "Odayeri BİM", unit: "TL" },
              { row: 173, label: "Hüseynili BİM", unit: "TL" },
              { row: 174, label: "Hyundai Binası", unit: "TL" },
              { row: 175, label: "Kimyasal", unit: "TL" },
              { row: 176, label: "Mesai Giderleri", unit: "TL" },
              { row: 177, label: "Ek Giderler (2 mobil ekip+araç+yakıt)", unit: "TL" },
            ],
          },
          {
            code: "kilyos", row: 179, label: "Kilyos",
            itemRows: [],
          },
        ],
        params: [
          { code: "ucret_oht_ekip_sorumlusu", row: 125, label: "OHT Ekip Sorumlusu Ücret",  unit: "TL" },
          { code: "ucret_oht_personel",        row: 126, label: "OHT Personel Ücret",         unit: "TL" },
          { code: "ucret_danisma",             row: 127, label: "Danışma Tarabya Yalı Ücret", unit: "TL" },
          { code: "ucret_temizlik_personel",   row: 128, label: "Temizlik Personel Ücret",    unit: "TL" },
          { code: "kisi_toplam",     row: 129, label: "Kişi Sayısı Toplam",       unit: "Kişi" },
          { code: "kisi_gyg",        row: 130, label: "GYG Kişi",                 unit: "Kişi" },
          { code: "kisi_gyg_akm",    row: 131, label: "AKM Binası Kişi",          unit: "Kişi" },
          { code: "kisi_gyg_pmo",    row: 132, label: "PMO Binası Kişi",          unit: "Kişi" },
          { code: "kisi_kamu",       row: 135, label: "Kamu Kişi",                unit: "Kişi" },
          { code: "kisi_kamu_kopru", row: 136, label: "Köprü Koruma Kişi",        unit: "Kişi" },
          { code: "kisi_kamu_kgm",   row: 137, label: "KGM Binası Kişi",          unit: "Kişi" },
          { code: "kisi_oht",        row: 138, label: "OHT Kişi",                 unit: "Kişi" },
          { code: "kisi_oht_main",   row: 139, label: "OHT Ana Kişi",             unit: "Kişi" },
          { code: "kisi_oht_ekip",   row: 140, label: "OHT Ekip Sorumlusu Kişi",  unit: "Kişi" },
          { code: "kisi_operasyon",  row: 141, label: "Operasyon Kişi",           unit: "Kişi" },
          { code: "kisi_ops_bah",    row: 142, label: "Bahçıvan Kişi",            unit: "Kişi" },
          { code: "kisi_ops_akm",    row: 143, label: "AKM Çevre Kişi",           unit: "Kişi" },
          { code: "kisi_ops_oda",    row: 144, label: "Odayeri BİM Kişi",         unit: "Kişi" },
          { code: "kisi_ops_hus",    row: 145, label: "Hüseynili BİM Kişi",       unit: "Kişi" },
          { code: "kisi_ops_hyu",    row: 146, label: "Hyundai Kişi",             unit: "Kişi" },
          { code: "kisi_ops_kim",    row: 147, label: "Kimyasal Kişi",            unit: "Kişi" },
        ],
      },
      yemek: {
        total: { row: 180, label: "Yemek Giderleri", unit: "TL Karşılığı" },
        depts: [
          {
            code: "ictas", row: 218, label: "İçtaş",
            itemRows: [
              { row: 219, label: "İçtaş Yemek", unit: "TL" },
            ],
          },
          {
            code: "operasyon", row: 220, label: "Operasyon",
            itemRows: [
              { row: 221, label: "CCN Güvenlik", unit: "TL" },
              { row: 222, label: "Taşeron",       unit: "TL" },
            ],
          },
          {
            code: "kamu", row: 224, label: "Kamu",
            itemRows: [
              { row: 225, label: "Karayolları",                        unit: "TL" },
              { row: 226, label: "Köprü Koruma (Emniyet) Poyraz",     unit: "TL" },
              { row: 227, label: "Sahil Güvenlik",                    unit: "TL" },
              { row: 228, label: "Diğer Kamu (İBB+PTT+Orman)",       unit: "TL" },
              { row: 229, label: "Asya Trafik Jandarma",              unit: "TL" },
              { row: 230, label: "Rumelihisarı Jandarma",             unit: "TL" },
            ],
          },
          {
            code: "gyg", row: 231, label: "GYG",
            itemRows: [
              { row: 232, label: "ICA",                  unit: "TL" },
              { row: 233, label: "Cafe Personeli Gideri", unit: "TL" },
            ],
          },
          {
            code: "kilyos", row: 237, label: "Kilyos",
            itemRows: [],
            // note: Kilyos is dominant (86% of total), single row, endeks-based
          },
        ],
        params: [
          { code: "birim_fiyat",     row: 181, label: "Birim Fiyat (TL/öğün)",       unit: "TL"   },
          { code: "ogun_toplam",     row: 185, label: "Günlük Öğün Sayısı Toplam",   unit: "Öğün" },
          { code: "ogun_gyg",        row: 186, label: "GYG Öğün",                    unit: "Öğün" },
          { code: "ogun_ictas",      row: 187, label: "İçtaş Öğün",                  unit: "Öğün" },
          { code: "ogun_operasyon",  row: 188, label: "Operasyon Öğün Toplam",        unit: "Öğün" },
          { code: "ogun_ops_ccn",    row: 189, label: "CCN Güvenlik Öğün",           unit: "Öğün" },
          { code: "ogun_ops_tase",   row: 190, label: "Taşeron Öğün",                unit: "Öğün" },
          { code: "ogun_kamu",       row: 192, label: "Kamu Öğün Toplam",            unit: "Öğün" },
          { code: "ogun_kamu_kara",  row: 193, label: "Karayolları Öğün",            unit: "Öğün" },
          { code: "ogun_kamu_kopru", row: 194, label: "Köprü Koruma Öğün",           unit: "Öğün" },
          { code: "ogun_kamu_sahil", row: 195, label: "Sahil Güvenlik Öğün",         unit: "Öğün" },
          { code: "ogun_kamu_diger", row: 196, label: "Diğer Kamu Öğün",             unit: "Öğün" },
          { code: "ogun_kamu_asya",  row: 197, label: "Asya Trafik Jandarma Öğün",  unit: "Öğün" },
          { code: "ogun_kamu_rume",  row: 198, label: "Rumelihisarı Jandarma Öğün", unit: "Öğün" },
          { code: "ogun_gyg_ica",    row: 199, label: "GYG Öğün Toplam",             unit: "Öğün" },
          { code: "gun_gyg",         row: 201, label: "Gün Sayısı GYG Ort.",         unit: "Gün"  },
          { code: "gun_ictas",       row: 202, label: "Gün Sayısı İçtaş",            unit: "Gün"  },
          { code: "gun_operasyon",   row: 204, label: "Operasyon Gün Ort.",           unit: "Gün"  },
          { code: "gun_kamu",        row: 208, label: "Kamu Gün Ort.",               unit: "Gün"  },
        ],
      },
      servis: {
        total: { row: 238, label: "Servis Giderleri", unit: "TL Karşılığı" },
        depts: [
          {
            code: "gyg", row: 239, label: "GYG",
            itemRows: [],
            // GYG = merkez binaları servisi. Rotalar detay blokları içinde (rows 295+)
          },
          {
            code: "operasyon", row: 240, label: "Operasyon",
            itemRows: [],
            // Operasyon = saha servisi. ~41 rota, rows 247-293 (özet), 295-603 (detay)
          },
          {
            code: "kilyos", row: 604, label: "Kilyos",
            itemRows: [],
          },
        ],
        params: [
          { code: "tufe_ufe_kumulatif", row: 241, label: "TÜFE+ÜFE Kümülatif Oran",            unit: "%",    noRound: true },
          { code: "tufe_ufe_uygulama",  row: 242, label: "TÜFE+ÜFE Uygulama Oranı (%70)",      unit: "%",    noRound: true },
          { code: "yakit_asim_bayrak",  row: 243, label: "Yakıt Aşım Bayrağı",                 unit: "Flag"              },
          { code: "yakit_uygulama",     row: 244, label: "Yakıt Uygulama Oranı (1/3)",          unit: "%",    noRound: true },
          { code: "asgari_ucret_fark",  row: 245, label: "Asgari Ücret Farkı (TL/araç)",        unit: "TL"                },
          { code: "birim_fiyat_ort",    row: 246, label: "Birim Fiyat Ort. (TL/araç/ay)",       unit: "TL"                },
          { code: "arac_sayisi",        row: 605, label: "Kiralık Araç Sayısı",                  unit: "Adet"              },
        ],
      },
      arac_kira: {
        total: { row: 606, label: "Araç Kira Giderleri", unit: "TL Karşılığı" },
        depts: [
          { code: "gyg", row: 608, label: "GYG", itemRows: [
            { row: 609, label: "34EDL575" },
            { row: 612, label: "34HNK388" },
            { row: 614, label: "34HNU161" },
            { row: 616, label: "34HNU204" },
            { row: 618, label: "34GDB900" },
            { row: 620, label: "34GDT416" },
            { row: 621, label: "34GVC914" },
            { row: 623, label: "06DYC177" },
            { row: 625, label: "34GDB904" },
            { row: 626, label: "06DZN249" },
            { row: 628, label: "34EUV590" },
            { row: 629, label: "34GNG619" },
          ] },
          { code: "operasyon", row: 635, label: "Operasyon", itemRows: [
            { row: 636, label: "34FNR882" },
            { row: 638, label: "34FUT671" },
            { row: 640, label: "34ERA357" },
            { row: 642, label: "34GFV016" },
            { row: 644, label: "34GFU990" },
            { row: 646, label: "34GFU958" },
            { row: 648, label: "34GFU930" },
            { row: 650, label: "06BTU425" },
            { row: 652, label: "34KNR243" },
            { row: 654, label: "34KNR257" },
            { row: 656, label: "34GAJ771" },
            { row: 657, label: "34FRB831" },
            { row: 658, label: "34FRB737" },
            { row: 659, label: "34FRB759" },
            { row: 660, label: "34FRB720" },
            { row: 661, label: "34FRB774" },
            { row: 662, label: "34FRB708" },
            { row: 663, label: "34FRB786" },
            { row: 664, label: "34FRB810" },
            { row: 665, label: "34FRB696" },
            { row: 666, label: "34FPM558" },
          ] },
          { code: "ictas",     row: 689, label: "İçtaş",     itemRows: [] },
          { code: "kamu", row: 711, label: "Kamu", itemRows: [
            { row: 712, label: "34FJH177" },
            { row: 714, label: "34HUS455" },
            { row: 716, label: "34DPV362" },
            { row: 717, label: "34GUG418" },
            { row: 718, label: "34MBH056" },
            { row: 720, label: "06EHU857" },
            { row: 722, label: "34MOS748" },
          ] },
          { code: "kilyos", row: 728, label: "Kilyos", itemRows: [
            { row: 729, label: "34FBL455" },
            { row: 730, label: "06CUM270" },
            { row: 731, label: "34GBF927" },
            { row: 732, label: "34FUT674" },
            { row: 733, label: "34GBF928" },
            { row: 734, label: "34FOJ089" },
            { row: 735, label: "34FYG355" },
            { row: 736, label: "34FHY835" },
            { row: 737, label: "34EYD862" },
            { row: 738, label: "34FOJ090" },
            { row: 739, label: "34EYD856" },
            { row: 740, label: "34EYD847" },
            { row: 741, label: "34FOJ716" },
            { row: 742, label: "34GBV820" },
            { row: 743, label: "34GBV797" },
            { row: 744, label: "34GHA899" },
            { row: 745, label: "34HYF982" },
            { row: 746, label: "34HJF473" },
            { row: 747, label: "34DUB697" },
            { row: 748, label: "34GYM528" },
            { row: 749, label: "06EFT609" },
            { row: 750, label: "34GGA761" },
            { row: 751, label: "34FRZ397" },
            { row: 752, label: "34HSV227" },
            { row: 753, label: "34HRU532" },
            { row: 754, label: "34HVE885" },
            { row: 755, label: "34FJC993" },
            { row: 756, label: "06EIV059" },
            { row: 757, label: "34FHY834" },
            { row: 758, label: "34HTF751" },
            { row: 759, label: "34FAP082" },
            { row: 760, label: "Yeni Araç 1" },
            { row: 761, label: "Yeni Araç 2" },
          ] },
        ],
        params: [
          { code: "arac_sayisi_gyg",  row: 607, label: "GYG Araç Sayısı",       unit: "Adet" },
          { code: "arac_sayisi_ops",  row: 632, label: "Operasyon Araç Sayısı",  unit: "Adet" },
          { code: "arac_sayisi_kamu", row: 710, label: "Kamu Araç Sayısı",       unit: "Adet" },
          { code: "arac_sayisi_kil",  row: 727, label: "Kilyos Araç Sayısı",     unit: "Adet" },
        ],
      },
      hgs: {
        total: { row: 785, label: "HGS Giderleri", unit: "TL Karşılığı" },
        depts: [
          { code: "gyg", row: 787, label: "Genel Yönetim", itemRows: [
            { row: 788, label: "Araç 1" },  { row: 791, label: "Araç 2" },
            { row: 793, label: "Araç 3" },  { row: 795, label: "Araç 4" },
            { row: 797, label: "Araç 5" },  { row: 799, label: "Araç 6" },
            { row: 800, label: "Araç 7" },  { row: 802, label: "Araç 8" },
            { row: 804, label: "Araç 9" },  { row: 805, label: "Araç 10" },
            { row: 807, label: "Araç 11" }, { row: 808, label: "Araç 12" },
          ] },
          { code: "operasyon", row: 815, label: "Operasyon", itemRows: [
            { row: 816, label: "Araç 1" },  { row: 818, label: "Araç 2" },
            { row: 820, label: "Araç 3" },  { row: 822, label: "Araç 4" },
            { row: 824, label: "Araç 5" },  { row: 826, label: "Araç 6" },
            { row: 828, label: "Araç 7" },  { row: 830, label: "Araç 8" },
            { row: 832, label: "Araç 9" },  { row: 834, label: "Araç 10" },
            { row: 836, label: "Araç 11" }, { row: 837, label: "Araç 12" },
            { row: 838, label: "Araç 13" }, { row: 839, label: "Araç 14" },
            { row: 840, label: "Araç 15" }, { row: 841, label: "Araç 16" },
            { row: 842, label: "Araç 17" }, { row: 843, label: "Araç 18" },
            { row: 844, label: "Araç 19" }, { row: 845, label: "Araç 20" },
            { row: 846, label: "Araç 21" },
          ] },
          { code: "operasyon_ictas",  row: 871, label: "Operasyon - İçtaş", itemRows: [] },
          { code: "kamu", row: 893, label: "Kamu", itemRows: [
            { row: 894, label: "Araç 1" }, { row: 896, label: "Araç 2" },
            { row: 898, label: "Araç 3" }, { row: 899, label: "Araç 4" },
            { row: 900, label: "Araç 5" }, { row: 902, label: "Araç 6" },
            { row: 905, label: "Araç 7" },
          ] },
          { code: "kilyos",           row: 910, label: "Kilyos",            itemRows: [] },
        ],
        params: [
          { code: "arac_sayisi_gyg",              row: 786, label: "GYG Araç Sayısı",             unit: "Adet" },
          { code: "arac_sayisi_operasyon",        row: 814, label: "Operasyon Araç Sayısı",       unit: "Adet" },
          { code: "arac_sayisi_operasyon_ictas",  row: 870, label: "Operasyon-İçtaş Araç Sayısı", unit: "Adet" },
          { code: "arac_sayisi_kamu",             row: 892, label: "Kamu Araç Sayısı",            unit: "Adet" },
          { code: "arac_sayisi_kilyos",           row: 909, label: "Kilyos Araç Sayısı",          unit: "Adet" },
        ],
      },
      arac_yakit: {
        total: { row: 970, label: "Araç Yakıt Giderleri", unit: "TL Karşılığı" },
        depts: [
          { code: "gyg", row: 973, label: "Genel Yönetim", itemRows: [], itemPairs: [
            [974,975],[980,981],[984,985],[988,989],[992,993],
            [994,995],[996,997],[1000,1001],[1004,1005],[1006,1007],[1012,1013],
          ] },
          { code: "operasyon", row: 1025, label: "Operasyon", itemRows: [], itemPairs: [
            [1026,1027],[1030,1031],[1038,1039],[1042,1043],[1046,1047],
            [1050,1051],[1058,1059],[1062,1063],[1066,1067],[1068,1069],
            [1070,1071],[1072,1073],[1073,1074],[1075,1076],[1078,1079],
            [1080,1081],[1082,1083],[1084,1085],[1086,1087],
          ] },
          { code: "kamu", row: 1128, label: "Kamu", itemRows: [], itemPairs: [
            [1129,1130],[1133,1134],[1137,1138],[1141,1142],[1145,1146],[1149,1150],
          ] },
        ],
        params: [
          { code: "arac_toplam",           row: 969,  label: "Toplam Araç Sayısı",    unit: "Adet",  noRound: false },
          { code: "birim_fiyat",           row: 971,  label: "Birim Fiyat (TL/L)",    unit: "TL/L",  noRound: true  },
          { code: "arac_sayisi_gyg",       row: 972,  label: "GYG Araç Sayısı",       unit: "Adet",  noRound: false },
          { code: "arac_sayisi_operasyon", row: 1024, label: "Operasyon Araç Sayısı", unit: "Adet",  noRound: false },
          { code: "arac_sayisi_kamu",      row: 1127, label: "Kamu Araç Sayısı",      unit: "Adet",  noRound: false },
        ],
      },
      arac_bakim: {
        total: { row: 1163, label: "Taşıt Bakım Onarım", unit: "TL Karşılığı" },
        depts: [
          { code: "gyg", row: 1165, label: "Genel Yönetim", itemRows: [
            { row: 1166, label: "Araç 1" },  { row: 1169, label: "Araç 2" },
            { row: 1171, label: "Araç 3" },  { row: 1173, label: "Araç 4" },
            { row: 1175, label: "Araç 5" },  { row: 1177, label: "Araç 6" },
            { row: 1178, label: "Araç 7" },  { row: 1180, label: "Araç 8" },
            { row: 1182, label: "Araç 9" },  { row: 1183, label: "Araç 10" },
            { row: 1185, label: "Araç 11" }, { row: 1186, label: "Araç 12" },
          ] },
          { code: "kamu", row: 1191, label: "Kamu", itemRows: [
            { row: 1192, label: "Araç 1" }, { row: 1194, label: "Araç 2" },
            { row: 1196, label: "Araç 3" }, { row: 1197, label: "Araç 4" },
            { row: 1198, label: "Araç 5" }, { row: 1200, label: "Araç 6" },
            { row: 1203, label: "Araç 7" },
          ] },
          { code: "operasyon", row: 1207, label: "Operasyon", itemRows: [
            { row: 1208, label: "Araç 1" },  { row: 1210, label: "Araç 2" },
            { row: 1212, label: "Araç 3" },  { row: 1214, label: "Araç 4" },
            { row: 1216, label: "Araç 5" },  { row: 1218, label: "Araç 6" },
            { row: 1220, label: "Araç 7" },  { row: 1222, label: "Araç 8" },
            { row: 1224, label: "Araç 9" },  { row: 1226, label: "Araç 10" },
            { row: 1228, label: "Araç 11" }, { row: 1229, label: "Araç 12" },
            { row: 1230, label: "Araç 13" }, { row: 1231, label: "Araç 14" },
            { row: 1232, label: "Araç 15" }, { row: 1233, label: "Araç 16" },
            { row: 1234, label: "Araç 17" }, { row: 1235, label: "Araç 18" },
            { row: 1236, label: "Araç 19" }, { row: 1237, label: "Araç 20" },
            { row: 1238, label: "Araç 21" },
          ] },
        ],
        params: [
          { code: "arac_toplam",           row: 1162, label: "Toplam Araç Sayısı",    unit: "Adet" },
          { code: "arac_sayisi_gyg",       row: 1164, label: "GYG Araç Sayısı",       unit: "Adet" },
          { code: "arac_sayisi_kamu",      row: 1190, label: "Kamu Araç Sayısı",      unit: "Adet" },
          { code: "arac_sayisi_operasyon", row: 1206, label: "Operasyon Araç Sayısı", unit: "Adet" },
        ],
      },
      diger_hizmet: {
        total: { row: 1273, label: "Diğer Hizmet Giderleri", unit: "TL Karşılığı" },
        depts: [
          { code: "bakim_merkezi", row: 1274, label: "Bakım Merkezi Grubu", itemRows: [] },
          { code: "vidanjor",      row: 1299, label: "Vidanjör/Fosseptik",  itemRows: [] },
          { code: "su_tankeri",    row: 1303, label: "Su Tankeri Grubu",    itemRows: [] },
        ],
        params: [
          // ── Bakım Merkezi ────────────────────────────────────────────
          { code: "kamyonet_cop",       row: 1275, label: "Kiralık Kamyonet Çöp Aracı",        unit: "TL",    deptCode: "bakim_merkezi" },
          { code: "kamyonet_fiyat",     row: 1276, label: "Kamyonet Birim Fiyat",              unit: "TL",    deptCode: "bakim_merkezi" },
          { code: "kamyonet_adet",      row: 1277, label: "Kamyonet Araç Sayısı",              unit: "Adet",  deptCode: "bakim_merkezi" },
          { code: "cop_avrupa_bakim",   row: 1278, label: "Çöp Döküm - Avrupa (Bakım)",        unit: "TL",    deptCode: "bakim_merkezi" },
          { code: "cop_avrupa_fiyat",   row: 1279, label: "Çöp Döküm Avrupa Birim Fiyat",      unit: "TL",    deptCode: "bakim_merkezi" },
          { code: "cop_avrupa_ton",     row: 1280, label: "Çöp Döküm Avrupa Ton",              unit: "Ton",   deptCode: "bakim_merkezi" },
          { code: "cop_asya_bakim",     row: 1281, label: "Çöp Döküm - Asya (Bakım)",          unit: "TL",    deptCode: "bakim_merkezi" },
          { code: "cop_asya_fiyat",     row: 1282, label: "Çöp Döküm Asya Birim Fiyat",        unit: "TL",    deptCode: "bakim_merkezi" },
          { code: "cop_asya_ton",       row: 1283, label: "Çöp Döküm Asya Ton",                unit: "Ton",   deptCode: "bakim_merkezi" },
          { code: "cop_avrupa_ica",     row: 1284, label: "Çöp Döküm - Avrupa (ICA+OHT)",      unit: "TL",    deptCode: "bakim_merkezi" },
          { code: "cop_avrupa_ica_f",   row: 1285, label: "Çöp Döküm Avrupa ICA Birim Fiyat",  unit: "TL",    deptCode: "bakim_merkezi" },
          { code: "cop_avrupa_ica_t",   row: 1286, label: "Çöp Döküm Avrupa ICA Ton",          unit: "Ton",   deptCode: "bakim_merkezi" },
          { code: "cop_asya_ica",       row: 1287, label: "Çöp Döküm - Asya (ICA+OHT)",        unit: "TL",    deptCode: "bakim_merkezi" },
          { code: "cop_asya_ica_f",     row: 1288, label: "Çöp Döküm Asya ICA Birim Fiyat",    unit: "TL",    deptCode: "bakim_merkezi" },
          { code: "cop_asya_ica_t",     row: 1289, label: "Çöp Döküm Asya ICA Ton",            unit: "Ton",   deptCode: "bakim_merkezi" },
          { code: "hafriyat_avrupa",    row: 1290, label: "Hafriyat Döküm - Avrupa",            unit: "TL",    deptCode: "bakim_merkezi" },
          { code: "hafriyat_avr_fiyat", row: 1291, label: "Hafriyat Avrupa Birim Fiyat",        unit: "TL",    deptCode: "bakim_merkezi" },
          { code: "hafriyat_avr_sefer", row: 1292, label: "Hafriyat Avrupa Sefer Sayısı",       unit: "Sefer", deptCode: "bakim_merkezi" },
          { code: "hafriyat_asya",      row: 1293, label: "Hafriyat Döküm - Asya",              unit: "TL",    deptCode: "bakim_merkezi" },
          { code: "hafriyat_asya_f",    row: 1294, label: "Hafriyat Asya Birim Fiyat",          unit: "TL",    deptCode: "bakim_merkezi" },
          { code: "hafriyat_asya_s",    row: 1295, label: "Hafriyat Asya Sefer Sayısı",         unit: "Sefer", deptCode: "bakim_merkezi" },
          { code: "kamyonet_oht_payi",  row: 1297, label: "Kiralık Kamyonet OHT Payı",          unit: "TL",    deptCode: "bakim_merkezi" },
          { code: "cop_oht_payi",       row: 1298, label: "Çöp Döküm OHT Payı",                 unit: "TL",    deptCode: "bakim_merkezi" },
          // ── Vidanjör ─────────────────────────────────────────────────
          { code: "vidanjor_fiyat",     row: 1300, label: "Vidanjör Birim Fiyat",               unit: "TL",    deptCode: "vidanjor" },
          { code: "vidanjor_adet",      row: 1301, label: "Vidanjör Araç Sayısı",               unit: "Adet",  deptCode: "vidanjor" },
          // ── Su Tankeri ───────────────────────────────────────────────
          { code: "su_tankeri_tutar",   row: 1304, label: "Su Tankeri Taşıma Suyu",             unit: "TL",    deptCode: "su_tankeri" },
          { code: "su_tankeri_fiyat",   row: 1305, label: "Su Tankeri Birim Fiyat",             unit: "TL",    deptCode: "su_tankeri" },
          { code: "su_tankeri_adet",    row: 1306, label: "Su Tankeri Araç Sayısı",             unit: "Adet",  deptCode: "su_tankeri" },
          { code: "su_nakliye",         row: 1309, label: "Su Nakliyesi (Gişeler+Kimyasal)",    unit: "TL",    deptCode: "su_tankeri" },
          { code: "su_nakliye_fiyat",   row: 1310, label: "Su Nakliye Birim Fiyat",             unit: "TL",    deptCode: "su_tankeri" },
          { code: "su_nakliye_litre",   row: 1311, label: "Su Nakliye Litre",                   unit: "Litre", deptCode: "su_tankeri" },
        ],
      },
      icme_suyu: {
        total: { row: 1312, label: "İçme Suyu Giderleri", unit: "TL Karşılığı" },
        depts: [
          { code: "gyg",    row: 1313, label: "GYG Toplam",        itemRows: [] },
          { code: "oht",    row: 1329, label: "OHT Toplam",         itemRows: [] },
          { code: "kilyos", row: 1336, label: "Kilyos İçme Suyu",  itemRows: [] },
        ],
        params: [
          // ── GYG ──────────────────────────────────────────────────────
          { code: "garipce_damacana",     row: 1314, label: "Garipçe Damacana",    unit: "TL",   noRound: true,  deptCode: "gyg" },
          { code: "garipce_dam_tuketim",  row: 1315, label: "Aylık Tüketim",       unit: "Adet", noRound: false, deptCode: "gyg" },
          { code: "garipce_dam_fiyat",    row: 1316, label: "Birim Fiyat",         unit: "TL",   noRound: true,  deptCode: "gyg" },
          { code: "garipce_pet",          row: 1317, label: "Garipçe PET 24'lü",   unit: "TL",   noRound: true,  deptCode: "gyg" },
          { code: "garipce_pet_tuketim",  row: 1318, label: "Aylık Tüketim",       unit: "Adet", noRound: false, deptCode: "gyg" },
          { code: "garipce_pet_fiyat",    row: 1319, label: "Birim Fiyat",         unit: "TL",   noRound: true,  deptCode: "gyg" },
          { code: "sade_soda",            row: 1320, label: "Sade Soda 24'lü",     unit: "TL",   noRound: true,  deptCode: "gyg" },
          { code: "sade_soda_tuketim",    row: 1321, label: "Aylık Tüketim",       unit: "Adet", noRound: false, deptCode: "gyg" },
          { code: "sade_soda_fiyat",      row: 1322, label: "Birim Fiyat",         unit: "TL",   noRound: true,  deptCode: "gyg" },
          { code: "meyveli_soda",         row: 1323, label: "Meyveli Soda 24'lü",  unit: "TL",   noRound: true,  deptCode: "gyg" },
          { code: "meyveli_soda_tuketim", row: 1324, label: "Aylık Tüketim",       unit: "Adet", noRound: false, deptCode: "gyg" },
          { code: "meyveli_soda_fiyat",   row: 1325, label: "Birim Fiyat",         unit: "TL",   noRound: true,  deptCode: "gyg" },
          { code: "cam_sise",             row: 1326, label: "Cam Şişe 12'li",      unit: "TL",   noRound: true,  deptCode: "gyg" },
          { code: "cam_sise_tuketim",     row: 1327, label: "Aylık Tüketim",       unit: "Adet", noRound: false, deptCode: "gyg" },
          { code: "cam_sise_fiyat",       row: 1328, label: "Birim Fiyat",         unit: "TL",   noRound: true,  deptCode: "gyg" },
          // ── OHT ──────────────────────────────────────────────────────
          { code: "oht_pet",              row: 1330, label: "OHT PET 24'lü",       unit: "TL",   noRound: true,  deptCode: "oht" },
          { code: "oht_pet_tuketim",      row: 1331, label: "Aylık Tüketim",       unit: "Adet", noRound: false, deptCode: "oht" },
          { code: "oht_pet_fiyat",        row: 1332, label: "Birim Fiyat",         unit: "TL",   noRound: true,  deptCode: "oht" },
          { code: "oht_damacana",         row: 1333, label: "OHT Damacana",        unit: "TL",   noRound: true,  deptCode: "oht" },
          { code: "oht_dam_tuketim",      row: 1334, label: "Aylık Tüketim",       unit: "Adet", noRound: false, deptCode: "oht" },
          { code: "oht_dam_fiyat",        row: 1335, label: "Birim Fiyat",         unit: "TL",   noRound: true,  deptCode: "oht" },
        ],
      },
      diger_cesitli: {
        total: { row: 1337, label: "Diğer Çeşitli Giderler", unit: "TL Karşılığı" },
        depts: [
          { code: "temizlik_malzeme", row: 1338, label: "Temizlik Malzemesi Giderleri",         itemRows: [] },
          { code: "kucuk_demirbas",   row: 1341, label: "Gider Yazılan Küçük Demirbaşlar",      itemRows: [] },
          { code: "cep_telefonu",     row: 1344, label: "Cep Telefonu Giderleri",               itemRows: [] },
          { code: "posta_kargo",      row: 1347, label: "Posta ve Kargo Giderleri",             itemRows: [] },
          { code: "cay_ocagi",        row: 1350, label: "Çay Ocağı Giderleri",                  itemRows: [] },
          { code: "kirtasiye",        row: 1353, label: "Kırtasiye Giderleri",                  itemRows: [] },
          { code: "sehirici_ulasim",  row: 1356, label: "Şehiriçi Ulaşım, Otopark",             itemRows: [] },
          { code: "diger_kamu",       row: 1358, label: "Diğer Çeşitli - Kamu Giderleri",       itemRows: [] },
        ],
        params: [],
      },
    },
  },
  "2415": {
    sheet: "Model",
    categories: {
      servis: {
        total: { row: 20, label: "Personel Servisi Giderleri", unit: "TL Karşılığı" },
        depts: [
          { code: "fenertepe_a", row: 58, label: "FENERTEPE A", itemRows: [] },
          { code: "fenertepe_b", row: 64, label: "FENERTEPE B", itemRows: [] },
          { code: "fenertepe_c", row: 70, label: "FENERTEPE C", itemRows: [] },
          { code: "isiklar", row: 76, label: "IŞIKLAR", itemRows: [] },
          { code: "uskumrukoy", row: 82, label: "USKUMRUKÖY", itemRows: [] },
          { code: "riva", row: 88, label: "RİVA", itemRows: [] },
          { code: "huseyinli_komurluk", row: 94, label: "HÜSEYİNLİ-KÖMÜRLÜK", itemRows: [] },
          { code: "resadiye", row: 100, label: "REŞADİYE", itemRows: [] },
          { code: "alemdag", row: 106, label: "ALEMDAĞ", itemRows: [] },
          { code: "pasakoy", row: 112, label: "PAŞAKÖY", itemRows: [] },
          { code: "mecidiye", row: 118, label: "MECİDİYE", itemRows: [] },
          { code: "kurnakoy", row: 124, label: "KURNAKÖY", itemRows: [] },
          { code: "havaalani_odayer", row: 130, label: "HAVAALANI ODAYER", itemRows: [] },
          { code: "buyukcekmece_beylikduzu_kucukcekmece", row: 136, label: "BÜYÜKÇEKMECE-BEYLİKDÜZÜ-KÜÇÜKÇEKMECE", itemRows: [] },
          { code: "sirinevler_bagcilar_ikitelli_basaksehir", row: 142, label: "ŞİRİNEVLER-BAĞCILAR-İKİTELLİ-BAŞAKŞEHİR", itemRows: [] },
          { code: "sultangazi_arnavutkoy", row: 148, label: "SULTANGAZİ ARNAVUTKÖY", itemRows: [] },
          { code: "bayrampasa_kasmpasa_mecidiyekoy_kagithane", row: 154, label: "BAYRAMPAŞA-KASMPAŞA-MECİDİYEKÖY-KAĞITHANE", itemRows: [] },
          { code: "sariyer_kagithane", row: 160, label: "SARIYER-KAĞITHANE", itemRows: [] },
          { code: "pendik", row: 166, label: "PENDİK", itemRows: [] },
          { code: "beykoz", row: 172, label: "BEYKOZ", itemRows: [] },
          { code: "uskudar", row: 178, label: "ÜSKÜDAR", itemRows: [] },
          { code: "maltepe", row: 184, label: "MALTEPE", itemRows: [] },
          { code: "cekmekoy", row: 190, label: "ÇEKMEKÖY", itemRows: [] },
          { code: "arnavutkoy", row: 196, label: "ARNAVUTKÖY", itemRows: [] },
          { code: "sultanbeyli", row: 202, label: "SULTANBEYLİ", itemRows: [] },
          { code: "bakim_merkezi_odayeri_garipce_vardiya", row: 208, label: "BAKIM MERKEZİ(ODAYERİ-GARİPÇE)(VARDİYA)", itemRows: [] },
          { code: "bakim_merkezi_huseyinli_garipce_vardiya", row: 214, label: "BAKIM MERKEZİ(HÜSEYİNLİ-GARİPÇE)(VARDİYA)", itemRows: [] },
          { code: "ccn_otoban_temizlik_odayeri", row: 220, label: "CCN OTOBAN TEMİZLİK ODAYERİ", itemRows: [] },
          { code: "ccn_otoban_temizlik_huseyinli", row: 226, label: "CCN OTOBAN TEMİZLİK HÜSEYİNLİ", itemRows: [] },
          { code: "kucukcekmece", row: 232, label: "KÜÇÜKÇEKMECE", itemRows: [] },
          { code: "arnavutkoy_2", row: 238, label: "ARNAVUTKÖY -2", itemRows: [] },
        ],
        params: [
          { code: "tufe_ufe_yarim", row: 21, label: "Ocak-Temmuz TÜFE+ÜFE / 2", unit: "%", noRound: true },
          { code: "tufe_ufe_uygulanan", row: 22, label: "TÜFE+ÜFE Uygulanacak Oran", unit: "%", noRound: true },
          { code: "yakit_bareme", row: 23, label: "Yakıt Artışı %10 Baremi", unit: "%", noRound: true },
          { code: "yakit_uygulanan", row: 24, label: "Yakıt Artışı Uygulanan", unit: "%", noRound: true },
          { code: "asgari_ucret_fark", row: 25, label: "Asgari Ücret Farkı", unit: "%", noRound: true },
          { code: "birim_fiyat_ort", row: 26, label: "Birim Fiyat Ortalama", unit: "TL", noRound: true },
          { code: "gun_sayisi__fenertepe_a", row: 59, label: "Gün Sayısı", unit: "Gün", deptCode: "fenertepe_a" },
          { code: "birim_fiyat__fenertepe_a", row: 60, label: "Birim Fiyat", unit: "TL", deptCode: "fenertepe_a", noRound: true },
          { code: "tufe_ufe_fark__fenertepe_a", row: 61, label: "TÜFE+ÜFE /2 Farkı", unit: "TL", deptCode: "fenertepe_a", noRound: true },
          { code: "yakit_fark__fenertepe_a", row: 62, label: "Yakıt Artış Tutarı", unit: "TL", deptCode: "fenertepe_a", noRound: true },
          { code: "asgari_fark__fenertepe_a", row: 63, label: "Asgari Ücret Farkı", unit: "TL", deptCode: "fenertepe_a", noRound: true },
          { code: "gun_sayisi__fenertepe_b", row: 65, label: "Gün Sayısı", unit: "Gün", deptCode: "fenertepe_b" },
          { code: "birim_fiyat__fenertepe_b", row: 66, label: "Birim Fiyat", unit: "TL", deptCode: "fenertepe_b", noRound: true },
          { code: "tufe_ufe_fark__fenertepe_b", row: 67, label: "TÜFE+ÜFE /2 Farkı", unit: "TL", deptCode: "fenertepe_b", noRound: true },
          { code: "yakit_fark__fenertepe_b", row: 68, label: "Yakıt Artış Tutarı", unit: "TL", deptCode: "fenertepe_b", noRound: true },
          { code: "asgari_fark__fenertepe_b", row: 69, label: "Asgari Ücret Farkı", unit: "TL", deptCode: "fenertepe_b", noRound: true },
          { code: "gun_sayisi__fenertepe_c", row: 71, label: "Gün Sayısı", unit: "Gün", deptCode: "fenertepe_c" },
          { code: "birim_fiyat__fenertepe_c", row: 72, label: "Birim Fiyat", unit: "TL", deptCode: "fenertepe_c", noRound: true },
          { code: "tufe_ufe_fark__fenertepe_c", row: 73, label: "TÜFE+ÜFE /2 Farkı", unit: "TL", deptCode: "fenertepe_c", noRound: true },
          { code: "yakit_fark__fenertepe_c", row: 74, label: "Yakıt Artış Tutarı", unit: "TL", deptCode: "fenertepe_c", noRound: true },
          { code: "asgari_fark__fenertepe_c", row: 75, label: "Asgari Ücret Farkı", unit: "TL", deptCode: "fenertepe_c", noRound: true },
          { code: "gun_sayisi__isiklar", row: 77, label: "Gün Sayısı", unit: "Gün", deptCode: "isiklar" },
          { code: "birim_fiyat__isiklar", row: 78, label: "Birim Fiyat", unit: "TL", deptCode: "isiklar", noRound: true },
          { code: "tufe_ufe_fark__isiklar", row: 79, label: "TÜFE+ÜFE /2 Farkı", unit: "TL", deptCode: "isiklar", noRound: true },
          { code: "yakit_fark__isiklar", row: 80, label: "Yakıt Artış Tutarı", unit: "TL", deptCode: "isiklar", noRound: true },
          { code: "asgari_fark__isiklar", row: 81, label: "Asgari Ücret Farkı", unit: "TL", deptCode: "isiklar", noRound: true },
          { code: "gun_sayisi__uskumrukoy", row: 83, label: "Gün Sayısı", unit: "Gün", deptCode: "uskumrukoy" },
          { code: "birim_fiyat__uskumrukoy", row: 84, label: "Birim Fiyat", unit: "TL", deptCode: "uskumrukoy", noRound: true },
          { code: "tufe_ufe_fark__uskumrukoy", row: 85, label: "TÜFE+ÜFE /2 Farkı", unit: "TL", deptCode: "uskumrukoy", noRound: true },
          { code: "yakit_fark__uskumrukoy", row: 86, label: "Yakıt Artış Tutarı", unit: "TL", deptCode: "uskumrukoy", noRound: true },
          { code: "asgari_fark__uskumrukoy", row: 87, label: "Asgari Ücret Farkı", unit: "TL", deptCode: "uskumrukoy", noRound: true },
          { code: "gun_sayisi__riva", row: 89, label: "Gün Sayısı", unit: "Gün", deptCode: "riva" },
          { code: "birim_fiyat__riva", row: 90, label: "Birim Fiyat", unit: "TL", deptCode: "riva", noRound: true },
          { code: "tufe_ufe_fark__riva", row: 91, label: "TÜFE+ÜFE /2 Farkı", unit: "TL", deptCode: "riva", noRound: true },
          { code: "yakit_fark__riva", row: 92, label: "Yakıt Artış Tutarı", unit: "TL", deptCode: "riva", noRound: true },
          { code: "asgari_fark__riva", row: 93, label: "Asgari Ücret Farkı", unit: "TL", deptCode: "riva", noRound: true },
          { code: "gun_sayisi__huseyinli_komurluk", row: 95, label: "Gün Sayısı", unit: "Gün", deptCode: "huseyinli_komurluk" },
          { code: "birim_fiyat__huseyinli_komurluk", row: 96, label: "Birim Fiyat", unit: "TL", deptCode: "huseyinli_komurluk", noRound: true },
          { code: "tufe_ufe_fark__huseyinli_komurluk", row: 97, label: "TÜFE+ÜFE /2 Farkı", unit: "TL", deptCode: "huseyinli_komurluk", noRound: true },
          { code: "yakit_fark__huseyinli_komurluk", row: 98, label: "Yakıt Artış Tutarı", unit: "TL", deptCode: "huseyinli_komurluk", noRound: true },
          { code: "asgari_fark__huseyinli_komurluk", row: 99, label: "Asgari Ücret Farkı", unit: "TL", deptCode: "huseyinli_komurluk", noRound: true },
          { code: "gun_sayisi__resadiye", row: 101, label: "Gün Sayısı", unit: "Gün", deptCode: "resadiye" },
          { code: "birim_fiyat__resadiye", row: 102, label: "Birim Fiyat", unit: "TL", deptCode: "resadiye", noRound: true },
          { code: "tufe_ufe_fark__resadiye", row: 103, label: "TÜFE+ÜFE /2 Farkı", unit: "TL", deptCode: "resadiye", noRound: true },
          { code: "yakit_fark__resadiye", row: 104, label: "Yakıt Artış Tutarı", unit: "TL", deptCode: "resadiye", noRound: true },
          { code: "asgari_fark__resadiye", row: 105, label: "Asgari Ücret Farkı", unit: "TL", deptCode: "resadiye", noRound: true },
          { code: "gun_sayisi__alemdag", row: 107, label: "Gün Sayısı", unit: "Gün", deptCode: "alemdag" },
          { code: "birim_fiyat__alemdag", row: 108, label: "Birim Fiyat", unit: "TL", deptCode: "alemdag", noRound: true },
          { code: "tufe_ufe_fark__alemdag", row: 109, label: "TÜFE+ÜFE /2 Farkı", unit: "TL", deptCode: "alemdag", noRound: true },
          { code: "yakit_fark__alemdag", row: 110, label: "Yakıt Artış Tutarı", unit: "TL", deptCode: "alemdag", noRound: true },
          { code: "asgari_fark__alemdag", row: 111, label: "Asgari Ücret Farkı", unit: "TL", deptCode: "alemdag", noRound: true },
          { code: "gun_sayisi__pasakoy", row: 113, label: "Gün Sayısı", unit: "Gün", deptCode: "pasakoy" },
          { code: "birim_fiyat__pasakoy", row: 114, label: "Birim Fiyat", unit: "TL", deptCode: "pasakoy", noRound: true },
          { code: "tufe_ufe_fark__pasakoy", row: 115, label: "TÜFE+ÜFE /2 Farkı", unit: "TL", deptCode: "pasakoy", noRound: true },
          { code: "yakit_fark__pasakoy", row: 116, label: "Yakıt Artış Tutarı", unit: "TL", deptCode: "pasakoy", noRound: true },
          { code: "asgari_fark__pasakoy", row: 117, label: "Asgari Ücret Farkı", unit: "TL", deptCode: "pasakoy", noRound: true },
          { code: "gun_sayisi__mecidiye", row: 119, label: "Gün Sayısı", unit: "Gün", deptCode: "mecidiye" },
          { code: "birim_fiyat__mecidiye", row: 120, label: "Birim Fiyat", unit: "TL", deptCode: "mecidiye", noRound: true },
          { code: "tufe_ufe_fark__mecidiye", row: 121, label: "TÜFE+ÜFE /2 Farkı", unit: "TL", deptCode: "mecidiye", noRound: true },
          { code: "yakit_fark__mecidiye", row: 122, label: "Yakıt Artış Tutarı", unit: "TL", deptCode: "mecidiye", noRound: true },
          { code: "asgari_fark__mecidiye", row: 123, label: "Asgari Ücret Farkı", unit: "TL", deptCode: "mecidiye", noRound: true },
          { code: "gun_sayisi__kurnakoy", row: 125, label: "Gün Sayısı", unit: "Gün", deptCode: "kurnakoy" },
          { code: "birim_fiyat__kurnakoy", row: 126, label: "Birim Fiyat", unit: "TL", deptCode: "kurnakoy", noRound: true },
          { code: "tufe_ufe_fark__kurnakoy", row: 127, label: "TÜFE+ÜFE /2 Farkı", unit: "TL", deptCode: "kurnakoy", noRound: true },
          { code: "yakit_fark__kurnakoy", row: 128, label: "Yakıt Artış Tutarı", unit: "TL", deptCode: "kurnakoy", noRound: true },
          { code: "asgari_fark__kurnakoy", row: 129, label: "Asgari Ücret Farkı", unit: "TL", deptCode: "kurnakoy", noRound: true },
          { code: "gun_sayisi__havaalani_odayer", row: 131, label: "Gün Sayısı", unit: "Gün", deptCode: "havaalani_odayer" },
          { code: "birim_fiyat__havaalani_odayer", row: 132, label: "Birim Fiyat", unit: "TL", deptCode: "havaalani_odayer", noRound: true },
          { code: "tufe_ufe_fark__havaalani_odayer", row: 133, label: "TÜFE+ÜFE /2 Farkı", unit: "TL", deptCode: "havaalani_odayer", noRound: true },
          { code: "yakit_fark__havaalani_odayer", row: 134, label: "Yakıt Artış Tutarı", unit: "TL", deptCode: "havaalani_odayer", noRound: true },
          { code: "asgari_fark__havaalani_odayer", row: 135, label: "Asgari Ücret Farkı", unit: "TL", deptCode: "havaalani_odayer", noRound: true },
          { code: "gun_sayisi__buyukcekmece_beylikduzu_kucukcekmece", row: 137, label: "Gün Sayısı", unit: "Gün", deptCode: "buyukcekmece_beylikduzu_kucukcekmece" },
          { code: "birim_fiyat__buyukcekmece_beylikduzu_kucukcekmece", row: 138, label: "Birim Fiyat", unit: "TL", deptCode: "buyukcekmece_beylikduzu_kucukcekmece", noRound: true },
          { code: "tufe_ufe_fark__buyukcekmece_beylikduzu_kucukcekmece", row: 139, label: "TÜFE+ÜFE /2 Farkı", unit: "TL", deptCode: "buyukcekmece_beylikduzu_kucukcekmece", noRound: true },
          { code: "yakit_fark__buyukcekmece_beylikduzu_kucukcekmece", row: 140, label: "Yakıt Artış Tutarı", unit: "TL", deptCode: "buyukcekmece_beylikduzu_kucukcekmece", noRound: true },
          { code: "asgari_fark__buyukcekmece_beylikduzu_kucukcekmece", row: 141, label: "Asgari Ücret Farkı", unit: "TL", deptCode: "buyukcekmece_beylikduzu_kucukcekmece", noRound: true },
          { code: "gun_sayisi__sirinevler_bagcilar_ikitelli_basaksehir", row: 143, label: "Gün Sayısı", unit: "Gün", deptCode: "sirinevler_bagcilar_ikitelli_basaksehir" },
          { code: "birim_fiyat__sirinevler_bagcilar_ikitelli_basaksehir", row: 144, label: "Birim Fiyat", unit: "TL", deptCode: "sirinevler_bagcilar_ikitelli_basaksehir", noRound: true },
          { code: "tufe_ufe_fark__sirinevler_bagcilar_ikitelli_basaksehir", row: 145, label: "TÜFE+ÜFE /2 Farkı", unit: "TL", deptCode: "sirinevler_bagcilar_ikitelli_basaksehir", noRound: true },
          { code: "yakit_fark__sirinevler_bagcilar_ikitelli_basaksehir", row: 146, label: "Yakıt Artış Tutarı", unit: "TL", deptCode: "sirinevler_bagcilar_ikitelli_basaksehir", noRound: true },
          { code: "asgari_fark__sirinevler_bagcilar_ikitelli_basaksehir", row: 147, label: "Asgari Ücret Farkı", unit: "TL", deptCode: "sirinevler_bagcilar_ikitelli_basaksehir", noRound: true },
          { code: "gun_sayisi__sultangazi_arnavutkoy", row: 149, label: "Gün Sayısı", unit: "Gün", deptCode: "sultangazi_arnavutkoy" },
          { code: "birim_fiyat__sultangazi_arnavutkoy", row: 150, label: "Birim Fiyat", unit: "TL", deptCode: "sultangazi_arnavutkoy", noRound: true },
          { code: "tufe_ufe_fark__sultangazi_arnavutkoy", row: 151, label: "TÜFE+ÜFE /2 Farkı", unit: "TL", deptCode: "sultangazi_arnavutkoy", noRound: true },
          { code: "yakit_fark__sultangazi_arnavutkoy", row: 152, label: "Yakıt Artış Tutarı", unit: "TL", deptCode: "sultangazi_arnavutkoy", noRound: true },
          { code: "asgari_fark__sultangazi_arnavutkoy", row: 153, label: "Asgari Ücret Farkı", unit: "TL", deptCode: "sultangazi_arnavutkoy", noRound: true },
          { code: "gun_sayisi__bayrampasa_kasmpasa_mecidiyekoy_kagithane", row: 155, label: "Gün Sayısı", unit: "Gün", deptCode: "bayrampasa_kasmpasa_mecidiyekoy_kagithane" },
          { code: "birim_fiyat__bayrampasa_kasmpasa_mecidiyekoy_kagithane", row: 156, label: "Birim Fiyat", unit: "TL", deptCode: "bayrampasa_kasmpasa_mecidiyekoy_kagithane", noRound: true },
          { code: "tufe_ufe_fark__bayrampasa_kasmpasa_mecidiyekoy_kagithane", row: 157, label: "TÜFE+ÜFE /2 Farkı", unit: "TL", deptCode: "bayrampasa_kasmpasa_mecidiyekoy_kagithane", noRound: true },
          { code: "yakit_fark__bayrampasa_kasmpasa_mecidiyekoy_kagithane", row: 158, label: "Yakıt Artış Tutarı", unit: "TL", deptCode: "bayrampasa_kasmpasa_mecidiyekoy_kagithane", noRound: true },
          { code: "asgari_fark__bayrampasa_kasmpasa_mecidiyekoy_kagithane", row: 159, label: "Asgari Ücret Farkı", unit: "TL", deptCode: "bayrampasa_kasmpasa_mecidiyekoy_kagithane", noRound: true },
          { code: "gun_sayisi__sariyer_kagithane", row: 161, label: "Gün Sayısı", unit: "Gün", deptCode: "sariyer_kagithane" },
          { code: "birim_fiyat__sariyer_kagithane", row: 162, label: "Birim Fiyat", unit: "TL", deptCode: "sariyer_kagithane", noRound: true },
          { code: "tufe_ufe_fark__sariyer_kagithane", row: 163, label: "TÜFE+ÜFE /2 Farkı", unit: "TL", deptCode: "sariyer_kagithane", noRound: true },
          { code: "yakit_fark__sariyer_kagithane", row: 164, label: "Yakıt Artış Tutarı", unit: "TL", deptCode: "sariyer_kagithane", noRound: true },
          { code: "asgari_fark__sariyer_kagithane", row: 165, label: "Asgari Ücret Farkı", unit: "TL", deptCode: "sariyer_kagithane", noRound: true },
          { code: "gun_sayisi__pendik", row: 167, label: "Gün Sayısı", unit: "Gün", deptCode: "pendik" },
          { code: "birim_fiyat__pendik", row: 168, label: "Birim Fiyat", unit: "TL", deptCode: "pendik", noRound: true },
          { code: "tufe_ufe_fark__pendik", row: 169, label: "TÜFE+ÜFE /2 Farkı", unit: "TL", deptCode: "pendik", noRound: true },
          { code: "yakit_fark__pendik", row: 170, label: "Yakıt Artış Tutarı", unit: "TL", deptCode: "pendik", noRound: true },
          { code: "asgari_fark__pendik", row: 171, label: "Asgari Ücret Farkı", unit: "TL", deptCode: "pendik", noRound: true },
          { code: "gun_sayisi__beykoz", row: 173, label: "Gün Sayısı", unit: "Gün", deptCode: "beykoz" },
          { code: "birim_fiyat__beykoz", row: 174, label: "Birim Fiyat", unit: "TL", deptCode: "beykoz", noRound: true },
          { code: "tufe_ufe_fark__beykoz", row: 175, label: "TÜFE+ÜFE /2 Farkı", unit: "TL", deptCode: "beykoz", noRound: true },
          { code: "yakit_fark__beykoz", row: 176, label: "Yakıt Artış Tutarı", unit: "TL", deptCode: "beykoz", noRound: true },
          { code: "asgari_fark__beykoz", row: 177, label: "Asgari Ücret Farkı", unit: "TL", deptCode: "beykoz", noRound: true },
          { code: "gun_sayisi__uskudar", row: 179, label: "Gün Sayısı", unit: "Gün", deptCode: "uskudar" },
          { code: "birim_fiyat__uskudar", row: 180, label: "Birim Fiyat", unit: "TL", deptCode: "uskudar", noRound: true },
          { code: "tufe_ufe_fark__uskudar", row: 181, label: "TÜFE+ÜFE /2 Farkı", unit: "TL", deptCode: "uskudar", noRound: true },
          { code: "yakit_fark__uskudar", row: 182, label: "Yakıt Artış Tutarı", unit: "TL", deptCode: "uskudar", noRound: true },
          { code: "asgari_fark__uskudar", row: 183, label: "Asgari Ücret Farkı", unit: "TL", deptCode: "uskudar", noRound: true },
          { code: "gun_sayisi__maltepe", row: 185, label: "Gün Sayısı", unit: "Gün", deptCode: "maltepe" },
          { code: "birim_fiyat__maltepe", row: 186, label: "Birim Fiyat", unit: "TL", deptCode: "maltepe", noRound: true },
          { code: "tufe_ufe_fark__maltepe", row: 187, label: "TÜFE+ÜFE /2 Farkı", unit: "TL", deptCode: "maltepe", noRound: true },
          { code: "yakit_fark__maltepe", row: 188, label: "Yakıt Artış Tutarı", unit: "TL", deptCode: "maltepe", noRound: true },
          { code: "asgari_fark__maltepe", row: 189, label: "Asgari Ücret Farkı", unit: "TL", deptCode: "maltepe", noRound: true },
          { code: "gun_sayisi__cekmekoy", row: 191, label: "Gün Sayısı", unit: "Gün", deptCode: "cekmekoy" },
          { code: "birim_fiyat__cekmekoy", row: 192, label: "Birim Fiyat", unit: "TL", deptCode: "cekmekoy", noRound: true },
          { code: "tufe_ufe_fark__cekmekoy", row: 193, label: "TÜFE+ÜFE /2 Farkı", unit: "TL", deptCode: "cekmekoy", noRound: true },
          { code: "yakit_fark__cekmekoy", row: 194, label: "Yakıt Artış Tutarı", unit: "TL", deptCode: "cekmekoy", noRound: true },
          { code: "asgari_fark__cekmekoy", row: 195, label: "Asgari Ücret Farkı", unit: "TL", deptCode: "cekmekoy", noRound: true },
          { code: "gun_sayisi__arnavutkoy", row: 197, label: "Gün Sayısı", unit: "Gün", deptCode: "arnavutkoy" },
          { code: "birim_fiyat__arnavutkoy", row: 198, label: "Birim Fiyat", unit: "TL", deptCode: "arnavutkoy", noRound: true },
          { code: "tufe_ufe_fark__arnavutkoy", row: 199, label: "TÜFE+ÜFE /2 Farkı", unit: "TL", deptCode: "arnavutkoy", noRound: true },
          { code: "yakit_fark__arnavutkoy", row: 200, label: "Yakıt Artış Tutarı", unit: "TL", deptCode: "arnavutkoy", noRound: true },
          { code: "asgari_fark__arnavutkoy", row: 201, label: "Asgari Ücret Farkı", unit: "TL", deptCode: "arnavutkoy", noRound: true },
          { code: "gun_sayisi__sultanbeyli", row: 203, label: "Gün Sayısı", unit: "Gün", deptCode: "sultanbeyli" },
          { code: "birim_fiyat__sultanbeyli", row: 204, label: "Birim Fiyat", unit: "TL", deptCode: "sultanbeyli", noRound: true },
          { code: "tufe_ufe_fark__sultanbeyli", row: 205, label: "TÜFE+ÜFE /2 Farkı", unit: "TL", deptCode: "sultanbeyli", noRound: true },
          { code: "yakit_fark__sultanbeyli", row: 206, label: "Yakıt Artış Tutarı", unit: "TL", deptCode: "sultanbeyli", noRound: true },
          { code: "asgari_fark__sultanbeyli", row: 207, label: "Asgari Ücret Farkı", unit: "TL", deptCode: "sultanbeyli", noRound: true },
          { code: "gun_sayisi__bakim_merkezi_odayeri_garipce_vardiya", row: 209, label: "Gün Sayısı", unit: "Gün", deptCode: "bakim_merkezi_odayeri_garipce_vardiya" },
          { code: "birim_fiyat__bakim_merkezi_odayeri_garipce_vardiya", row: 210, label: "Birim Fiyat", unit: "TL", deptCode: "bakim_merkezi_odayeri_garipce_vardiya", noRound: true },
          { code: "tufe_ufe_fark__bakim_merkezi_odayeri_garipce_vardiya", row: 211, label: "TÜFE+ÜFE /2 Farkı", unit: "TL", deptCode: "bakim_merkezi_odayeri_garipce_vardiya", noRound: true },
          { code: "yakit_fark__bakim_merkezi_odayeri_garipce_vardiya", row: 212, label: "Yakıt Artış Tutarı", unit: "TL", deptCode: "bakim_merkezi_odayeri_garipce_vardiya", noRound: true },
          { code: "asgari_fark__bakim_merkezi_odayeri_garipce_vardiya", row: 213, label: "Asgari Ücret Farkı", unit: "TL", deptCode: "bakim_merkezi_odayeri_garipce_vardiya", noRound: true },
          { code: "gun_sayisi__bakim_merkezi_huseyinli_garipce_vardiya", row: 215, label: "Gün Sayısı", unit: "Gün", deptCode: "bakim_merkezi_huseyinli_garipce_vardiya" },
          { code: "birim_fiyat__bakim_merkezi_huseyinli_garipce_vardiya", row: 216, label: "Birim Fiyat", unit: "TL", deptCode: "bakim_merkezi_huseyinli_garipce_vardiya", noRound: true },
          { code: "tufe_ufe_fark__bakim_merkezi_huseyinli_garipce_vardiya", row: 217, label: "TÜFE+ÜFE /2 Farkı", unit: "TL", deptCode: "bakim_merkezi_huseyinli_garipce_vardiya", noRound: true },
          { code: "yakit_fark__bakim_merkezi_huseyinli_garipce_vardiya", row: 218, label: "Yakıt Artış Tutarı", unit: "TL", deptCode: "bakim_merkezi_huseyinli_garipce_vardiya", noRound: true },
          { code: "asgari_fark__bakim_merkezi_huseyinli_garipce_vardiya", row: 219, label: "Asgari Ücret Farkı", unit: "TL", deptCode: "bakim_merkezi_huseyinli_garipce_vardiya", noRound: true },
          { code: "gun_sayisi__ccn_otoban_temizlik_odayeri", row: 221, label: "Gün Sayısı", unit: "Gün", deptCode: "ccn_otoban_temizlik_odayeri" },
          { code: "birim_fiyat__ccn_otoban_temizlik_odayeri", row: 222, label: "Birim Fiyat", unit: "TL", deptCode: "ccn_otoban_temizlik_odayeri", noRound: true },
          { code: "tufe_ufe_fark__ccn_otoban_temizlik_odayeri", row: 223, label: "TÜFE+ÜFE /2 Farkı", unit: "TL", deptCode: "ccn_otoban_temizlik_odayeri", noRound: true },
          { code: "yakit_fark__ccn_otoban_temizlik_odayeri", row: 224, label: "Yakıt Artış Tutarı", unit: "TL", deptCode: "ccn_otoban_temizlik_odayeri", noRound: true },
          { code: "asgari_fark__ccn_otoban_temizlik_odayeri", row: 225, label: "Asgari Ücret Farkı", unit: "TL", deptCode: "ccn_otoban_temizlik_odayeri", noRound: true },
          { code: "gun_sayisi__ccn_otoban_temizlik_huseyinli", row: 227, label: "Gün Sayısı", unit: "Gün", deptCode: "ccn_otoban_temizlik_huseyinli" },
          { code: "birim_fiyat__ccn_otoban_temizlik_huseyinli", row: 228, label: "Birim Fiyat", unit: "TL", deptCode: "ccn_otoban_temizlik_huseyinli", noRound: true },
          { code: "tufe_ufe_fark__ccn_otoban_temizlik_huseyinli", row: 229, label: "TÜFE+ÜFE /2 Farkı", unit: "TL", deptCode: "ccn_otoban_temizlik_huseyinli", noRound: true },
          { code: "yakit_fark__ccn_otoban_temizlik_huseyinli", row: 230, label: "Yakıt Artış Tutarı", unit: "TL", deptCode: "ccn_otoban_temizlik_huseyinli", noRound: true },
          { code: "asgari_fark__ccn_otoban_temizlik_huseyinli", row: 231, label: "Asgari Ücret Farkı", unit: "TL", deptCode: "ccn_otoban_temizlik_huseyinli", noRound: true },
          { code: "gun_sayisi__kucukcekmece", row: 233, label: "Gün Sayısı", unit: "Gün", deptCode: "kucukcekmece" },
          { code: "birim_fiyat__kucukcekmece", row: 234, label: "Birim Fiyat", unit: "TL", deptCode: "kucukcekmece", noRound: true },
          { code: "tufe_ufe_fark__kucukcekmece", row: 235, label: "TÜFE+ÜFE /2 Farkı", unit: "TL", deptCode: "kucukcekmece", noRound: true },
          { code: "yakit_fark__kucukcekmece", row: 236, label: "Yakıt Artış Tutarı", unit: "TL", deptCode: "kucukcekmece", noRound: true },
          { code: "asgari_fark__kucukcekmece", row: 237, label: "Asgari Ücret Farkı", unit: "TL", deptCode: "kucukcekmece", noRound: true },
          { code: "gun_sayisi__arnavutkoy_2", row: 239, label: "Gün Sayısı", unit: "Gün", deptCode: "arnavutkoy_2" },
          { code: "birim_fiyat__arnavutkoy_2", row: 240, label: "Birim Fiyat", unit: "TL", deptCode: "arnavutkoy_2", noRound: true },
          { code: "tufe_ufe_fark__arnavutkoy_2", row: 241, label: "TÜFE+ÜFE /2 Farkı", unit: "TL", deptCode: "arnavutkoy_2", noRound: true },
          { code: "yakit_fark__arnavutkoy_2", row: 242, label: "Yakıt Artış Tutarı", unit: "TL", deptCode: "arnavutkoy_2", noRound: true },
          { code: "asgari_fark__arnavutkoy_2", row: 243, label: "Asgari Ücret Farkı", unit: "TL", deptCode: "arnavutkoy_2", noRound: true },
        ],
      },
      yemek: {
        total: { row: 246, label: "Personel Yemek Giderleri", unit: "TL Karşılığı" },
        depts: [
          {
            code: "default", row: 289, label: "Yemek Organizasyonları", virtual: true,
            itemRows: [
              { row: 290, label: "ICA ALTYAPI", unit: "TL" },
              { row: 291, label: "ALTYAPI TAŞERON", unit: "TL" },
              { row: 292, label: "SAHUR", unit: "TL" },
              { row: 293, label: "İFTAR", unit: "TL" },
              { row: 294, label: "İFTAR YEMEĞİ BİM", unit: "TL" },
              { row: 295, label: "BAKIM MERKEZİ MANGAL ORG.", unit: "TL" },
              { row: 296, label: "CCN PEYZAJ", unit: "TL" },
              { row: 297, label: "ODAYERİ CCN", unit: "TL" },
              { row: 298, label: "HÜSEYİNLİ CCN", unit: "TL" },
              { row: 299, label: "KARLA MÜCADELE KUMANYA", unit: "TL" },
              { row: 300, label: "İDARİ İŞLER PERSONELİ ORGANİZASYON KAHVALTI", unit: "TL" },
              { row: 301, label: "İDARİ İŞLER PERSONELİ ORGANİZASYON YEMEK", unit: "TL" },
            ],
          },
        ],
        params: [
          { code: "asgari_fark_pct",      row: 249, label: "Asgari ücret farkı (%30)",       unit: "%", noRound: true },
          { code: "tufe_ufe_fark_pct",    row: 250, label: "TÜFE-ÜFE /2 farkı (%45)",         unit: "%", noRound: true },
          { code: "gida_endeks_fark_pct", row: 251, label: "Gıda Endeksi farkı (%25)",        unit: "%", noRound: true },
          { code: "bf_y_ica_altyapi",     row: 248, label: "Birim Fiyat - ICA ALTYAPI",       unit: "TL", noRound: true },
          { code: "bf_y_altyapi_taseron", row: 252, label: "Birim Fiyat - ALTYAPI TAŞERON",   unit: "TL", noRound: true },
          { code: "bf_y_sahur",           row: 253, label: "Birim Fiyat - SAHUR",             unit: "TL", noRound: true },
          { code: "bf_y_iftar",           row: 254, label: "Birim Fiyat - İFTAR",             unit: "TL", noRound: true },
          { code: "bf_y_iftar_yemegi_bim",row: 255, label: "Birim Fiyat - İFTAR YEMEĞİ BİM", unit: "TL", noRound: true },
          { code: "bf_y_bakim_merkezi_mangal_org", row: 256, label: "Birim Fiyat - BAKIM MERKEZİ MANGAL ORG.", unit: "TL", noRound: true },
          { code: "bf_y_ccn_peyzaj",      row: 257, label: "Birim Fiyat - CCN PEYZAJ",        unit: "TL", noRound: true },
          { code: "bf_y_odayeri_ccn",     row: 258, label: "Birim Fiyat - ODAYERİ CCN",       unit: "TL", noRound: true },
          { code: "bf_y_huseyinli_ccn",   row: 259, label: "Birim Fiyat - HÜSEYİNLİ CCN",    unit: "TL", noRound: true },
          { code: "bf_y_karla_mucadele_kumanya", row: 260, label: "Birim Fiyat - KARLA MÜCADELE KUMANYA", unit: "TL", noRound: true },
          { code: "bf_y_idari_isler_personeli_organizasyon_kahvalti", row: 261, label: "Birim Fiyat - İDARİ İŞLER PERSONELİ ORGANİZASYON KAHVALTI", unit: "TL", noRound: true },
          { code: "bf_y_idari_isler_personeli_organizasyon_yemek", row: 262, label: "Birim Fiyat - İDARİ İŞLER PERSONELİ ORGANİZASYON YEMEK", unit: "TL", noRound: true },
          { code: "ogun_y_ica_altyapi",   row: 264, label: "Öğün - ICA ALTYAPI",              unit: "Öğün" },
          { code: "ogun_y_altyapi_taseron", row: 265, label: "Öğün - ALTYAPI TAŞERON",        unit: "Öğün" },
          { code: "ogun_y_sahur",         row: 266, label: "Öğün - SAHUR",                    unit: "Öğün" },
          { code: "ogun_y_iftar",         row: 267, label: "Öğün - İFTAR",                    unit: "Öğün" },
          { code: "ogun_y_iftar_yemegi_bim", row: 268, label: "Öğün - İFTAR YEMEĞİ BİM",    unit: "Öğün" },
          { code: "ogun_y_bakim_merkezi_mangal_org", row: 269, label: "Öğün - BAKIM MERKEZİ MANGAL ORG.", unit: "Öğün" },
          { code: "ogun_y_ccn_peyzaj",    row: 270, label: "Öğün - CCN PEYZAJ",               unit: "Öğün" },
          { code: "ogun_y_odayeri_ccn",   row: 271, label: "Öğün - ODAYERİ CCN",              unit: "Öğün" },
          { code: "ogun_y_huseyinli_ccn", row: 272, label: "Öğün - HÜSEYİNLİ CCN",           unit: "Öğün" },
          { code: "ogun_y_karla_mucadele_kumanya", row: 273, label: "Öğün - KARLA MÜCADELE KUMANYA", unit: "Öğün" },
          { code: "ogun_y_idari_isler_personeli_organizasyon_kahvalti", row: 274, label: "Öğün - İDARİ İŞLER PERSONELİ ORGANİZASYON KAHVALTI", unit: "Öğün" },
          { code: "ogun_y_idari_isler_personeli_organizasyon_yemek", row: 275, label: "Öğün - İDARİ İŞLER PERSONELİ ORGANİZASYON YEMEK", unit: "Öğün" },
          { code: "ogun_toplam",          row: 263, label: "Toplam Öğün Sayısı",               unit: "Öğün" },
          { code: "gun_y_ica_altyapi",    row: 277, label: "Gün - ICA ALTYAPI",               unit: "Gün" },
          { code: "gun_y_altyapi_taseron",row: 278, label: "Gün - ALTYAPI TAŞERON",           unit: "Gün" },
          { code: "gun_y_sahur",          row: 279, label: "Gün - SAHUR",                     unit: "Gün" },
          { code: "gun_y_iftar",          row: 280, label: "Gün - İFTAR",                     unit: "Gün" },
          { code: "gun_y_iftar_yemegi_bim", row: 281, label: "Gün - İFTAR YEMEĞİ BİM",      unit: "Gün" },
          { code: "gun_y_bakim_merkezi_mangal_org", row: 282, label: "Gün - BAKIM MERKEZİ MANGAL ORG.", unit: "Gün" },
          { code: "gun_y_ccn_peyzaj",     row: 283, label: "Gün - CCN PEYZAJ",                unit: "Gün" },
          { code: "gun_y_odayeri_ccn",    row: 284, label: "Gün - ODAYERİ CCN",               unit: "Gün" },
          { code: "gun_y_huseyinli_ccn",  row: 285, label: "Gün - HÜSEYİNLİ CCN",            unit: "Gün" },
          { code: "gun_y_karla_mucadele_kumanya", row: 286, label: "Gün - KARLA MÜCADELE KUMANYA", unit: "Gün" },
          { code: "gun_y_idari_isler_personeli_organizasyon_kahvalti", row: 287, label: "Gün - İDARİ İŞLER PERSONELİ ORGANİZASYON KAHVALTI", unit: "Gün" },
          { code: "gun_y_idari_isler_personeli_organizasyon_yemek", row: 288, label: "Gün - İDARİ İŞLER PERSONELİ ORGANİZASYON YEMEK", unit: "Gün" },
        ],
      },
      arac_yakit: {
        total: { row: 303, label: "Araç Yakıt Giderleri", unit: "TL Karşılığı" },
        depts: [
          {
            code: "ana", row: 303, label: "İdari İşler (Ana)", virtual: true, itemRows: [],
            itemPairs: [
              [329, 306], [330, 307], [331, 308], [332, 309], [333, 310],
              [335, 312], [336, 313], [337, 314], [338, 315], [339, 316],
              [341, 318], [343, 320], [344, 321],
              [348, 325], [349, 326], [350, 327],
            ],
          },
          {
            code: "now", row: 303, label: "NOW Plaza", virtual: true, itemRows: [],
            itemPairs: [
              [342, 319], [345, 322], [346, 323], [347, 324],
            ],
          },
          {
            code: "ic", row: 303, label: "Diğer / İçtaş", virtual: true, itemRows: [],
            itemPairs: [
              [334, 311], [340, 317],
            ],
          },
        ],
        params: [
          { code: "birim_fiyat_yakit", row: 304, label: "Birim Fiyat (TL/L)", unit: "TL/L", noRound: true },
          { code: "toplam_litre",      row: 305, label: "Toplam Litre",        unit: "Litre" },
        ],
      },
      icme_suyu: {
        total: { row: 352, label: "Su Giderleri", unit: "TL Karşılığı" },
        depts: [
          {
            code: "giseler", row: 352, label: "Gişeler", virtual: true,
            itemRows: [
              { row: 372, label: "Damacana", unit: "TL" },
              { row: 373, label: "PET", unit: "TL" },
              { row: 374, label: "Sade Soda", unit: "TL" },
              { row: 375, label: "Meyveli Soda", unit: "TL" },
            ],
          },
          {
            code: "bkm", row: 352, label: "BKM", virtual: true,
            itemRows: [
              { row: 376, label: "Damacana", unit: "TL" },
              { row: 377, label: "PET", unit: "TL" },
              { row: 378, label: "Sade Soda", unit: "TL" },
              { row: 379, label: "Meyveli Soda", unit: "TL" },
            ],
          },
          {
            code: "kimyasal", row: 352, label: "Kimyasal", virtual: true,
            itemRows: [
              { row: 380, label: "Damacana", unit: "TL" },
              { row: 381, label: "PET", unit: "TL" },
              { row: 382, label: "Sade Soda", unit: "TL" },
              { row: 383, label: "Meyveli Soda", unit: "TL" },
            ],
          },
        ],
        params: [
          { code: "bf_damacana",     row: 354, label: "Birim Fiyat - Damacana",     unit: "TL", noRound: true },
          { code: "bf_pet",          row: 355, label: "Birim Fiyat - PET",           unit: "TL", noRound: true },
          { code: "bf_sade_soda",    row: 356, label: "Birim Fiyat - Sade Soda",    unit: "TL", noRound: true },
          { code: "bf_meyveli_soda", row: 357, label: "Birim Fiyat - Meyveli Soda", unit: "TL", noRound: true },
          { code: "adet_giseler_damacana",     row: 359, label: "Adet", unit: "Adet", deptCode: "giseler" },
          { code: "adet_giseler_pet",          row: 360, label: "Adet", unit: "Adet", deptCode: "giseler" },
          { code: "adet_giseler_sade_soda",    row: 361, label: "Adet", unit: "Adet", deptCode: "giseler" },
          { code: "adet_giseler_meyveli_soda", row: 362, label: "Adet", unit: "Adet", deptCode: "giseler" },
          { code: "adet_bkm_damacana",         row: 363, label: "Adet", unit: "Adet", deptCode: "bkm" },
          { code: "adet_bkm_pet",              row: 364, label: "Adet", unit: "Adet", deptCode: "bkm" },
          { code: "adet_bkm_sade_soda",        row: 365, label: "Adet", unit: "Adet", deptCode: "bkm" },
          { code: "adet_bkm_meyveli_soda",     row: 366, label: "Adet", unit: "Adet", deptCode: "bkm" },
          { code: "adet_kimyasal_damacana",     row: 367, label: "Adet", unit: "Adet", deptCode: "kimyasal" },
          { code: "adet_kimyasal_pet",          row: 368, label: "Adet", unit: "Adet", deptCode: "kimyasal" },
          { code: "adet_kimyasal_sade_soda",    row: 369, label: "Adet", unit: "Adet", deptCode: "kimyasal" },
          { code: "adet_kimyasal_meyveli_soda", row: 370, label: "Adet", unit: "Adet", deptCode: "kimyasal" },
        ],
      },
      arac_bakim: {
        total: { row: 386, label: "Araç Bakım Giderleri", unit: "TL Karşılığı" },
        depts: [
          {
            code: "ana", row: 386, label: "Ana", virtual: true,
            itemRows: [
              { row: 388, label: "KÖPRÜ BAKIM -34 ETA 214", unit: "TL" },
              { row: 389, label: "34MRS610", unit: "TL" },
              { row: 390, label: "KÖPRÜ KORUMA ŞUBESİ-34 GST 148", unit: "TL" },
              { row: 391, label: "ODAYERİ BAKIM İŞLETME ŞEFLİĞİ-34 GSS 602", unit: "TL" },
              { row: 393, label: "HÜSEYİNLİ BAKIM İŞLETME ŞEFLİĞİ-34 GSR 992", unit: "TL" },
              { row: 394, label: "34 NHN 664", unit: "TL" },
              { row: 395, label: "İDARİ İŞLER-34 EVP 212", unit: "TL" },
              { row: 396, label: "HÜSEYİNLİ BAKIM İŞLETME ŞEFLİĞİ-34 KJA 117", unit: "TL" },
              { row: 397, label: "ELEKTROMEKANİK-34 KIZ 814", unit: "TL" },
              { row: 398, label: "ELEKTROMEKANİK-34 KIZ 367", unit: "TL" },
              { row: 399, label: "MAKİNE-ATÖLYE-34 KJA 490", unit: "TL" },
              { row: 400, label: "OPERASYON DİREKTÖRÜ-34 KMC 892", unit: "TL" },
              { row: 401, label: "34NNV750", unit: "TL" },
              { row: 402, label: "İSG-34 KKR 726", unit: "TL" },
              { row: 403, label: "AMBAR-34 KKR 711", unit: "TL" },
              { row: 404, label: "TESİS BAKIM-34 KKR 610", unit: "TL" },
              { row: 405, label: "PEYZAJ-34 KKR 567", unit: "TL" },
              { row: 406, label: "ODAYERİ BAKIM-34 KKR 640", unit: "TL" },
              { row: 407, label: "İDARİ İŞLER-34 KKR 747", unit: "TL" },
              { row: 408, label: "OTOYOL BAKIM KIDEMLİ MÜDÜRÜ-34 KNR 265", unit: "TL" },
              { row: 409, label: "GİŞE OPERASYONLARI VE İDARİ İŞLER KIDEMLİ  MÜDÜRÜ-34 KNR 306", unit: "TL" },
              { row: 410, label: "YÖNETİM SİSTEMLERİ VE RİSK YÖNETİMİ-34 KTB 406", unit: "TL" },
              { row: 411, label: "TRAFİK GÜVENLİĞİ-34KEP207", unit: "TL" },
              { row: 414, label: "ELEKTROMEKANİK-06 EMY 030", unit: "TL" },
              { row: 416, label: "34MBR658 ISG", unit: "TL" },
              { row: 418, label: "34NFY640- FATİH KARAKURT", unit: "TL" },
              { row: 419, label: "34NGE928 - ELEKTROMEKANİK", unit: "TL" },
              { row: 420, label: "34GAU700- HALİL OMAY", unit: "TL" },
              { row: 424, label: "GİŞE OPERASYONLARI", unit: "TL" },
              { row: 425, label: "NOW PLAZA YERİNE HAVUZA ALINACAK ARAÇ", unit: "TL" },
              { row: 426, label: "ISG", unit: "TL" },
            ],
          },
          {
            code: "now", row: 386, label: "NOW Plaza", virtual: true,
            itemRows: [
              { row: 392, label: "34NHN644", unit: "TL" },
              { row: 421, label: "İSMAİL YİĞİT-34NOG217", unit: "TL" },
              { row: 422, label: "HALİM ÖZGÜN ALEMDAR-34PEE298", unit: "TL" },
              { row: 423, label: "HAVUZ ARACI-34MRZ308", unit: "TL" },
            ],
          },
          {
            code: "ic", row: 386, label: "Diğer / İçtaş", virtual: true,
            itemRows: [
              { row: 412, label: "***-34HRL696", unit: "TL" },
              { row: 413, label: "****-34 YSS 79", unit: "TL" },
              { row: 415, label: "34MTC538 NEZEHAT ÇEÇEN", unit: "TL" },
              { row: 417, label: "34MBK196 ZAFER HAVALİMANI", unit: "TL" },
              { row: 427, label: "ZAFER HAVALİMANI-NUH332", unit: "TL" },
            ],
          },
        ],
        params: [],
      },
      hgs: {
        total: { row: 428, label: "Araç HGS Giderleri", unit: "TL Karşılığı" },
        depts: [
          {
            code: "ana", row: 428, label: "Ana", virtual: true,
            itemRows: [
              { row: 429, label: "KÖPRÜ BAKIM -34 ETA 214", unit: "TL" },
              { row: 430, label: "34MRS610", unit: "TL" },
              { row: 431, label: "KÖPRÜ KORUMA ŞUBESİ-34 GST 148", unit: "TL" },
              { row: 432, label: "ODAYERİ BAKIM İŞLETME ŞEFLİĞİ-34 GSS 602", unit: "TL" },
              { row: 434, label: "HÜSEYİNLİ BAKIM İŞLETME ŞEFLİĞİ-34 GSR 992", unit: "TL" },
              { row: 435, label: "34 NHN 664", unit: "TL" },
              { row: 436, label: "İDARİ İŞLER-34 EVP 212", unit: "TL" },
              { row: 437, label: "HÜSEYİNLİ BAKIM İŞLETME ŞEFLİĞİ-34 KJA 117", unit: "TL" },
              { row: 438, label: "ELEKTROMEKANİK-34 KIZ 814", unit: "TL" },
              { row: 439, label: "ELEKTROMEKANİK-34 KIZ 367", unit: "TL" },
              { row: 440, label: "MAKİNE-ATÖLYE-34 KJA 490", unit: "TL" },
              { row: 441, label: "OPERASYON DİREKTÖRÜ-34 KMC 892", unit: "TL" },
              { row: 442, label: "34NNV750", unit: "TL" },
              { row: 443, label: "İSG-34 KKR 726", unit: "TL" },
              { row: 444, label: "AMBAR-34 KKR 711", unit: "TL" },
              { row: 445, label: "TESİS BAKIM-34 KKR 610", unit: "TL" },
              { row: 446, label: "PEYZAJ-34 KKR 567", unit: "TL" },
              { row: 447, label: "ODAYERİ BAKIM-34 KKR 640", unit: "TL" },
              { row: 448, label: "İDARİ İŞLER-34 KKR 747", unit: "TL" },
              { row: 449, label: "OTOYOL BAKIM KIDEMLİ MÜDÜRÜ-34 KNR 265", unit: "TL" },
              { row: 450, label: "GİŞE OPERASYONLARI VE İDARİ İŞLER KIDEMLİ  MÜDÜRÜ-34 KNR 306", unit: "TL" },
              { row: 451, label: "YÖNETİM SİSTEMLERİ VE RİSK YÖNETİMİ-34 KTB 406", unit: "TL" },
              { row: 452, label: "TRAFİK GÜVENLİĞİ-34 KEP 207", unit: "TL" },
              { row: 455, label: "ELEKTROMEKANİK-06 EMY 030", unit: "TL" },
              { row: 457, label: "34MBR658 ISG", unit: "TL" },
              { row: 459, label: "34NFY640- FATİH KARAKURT", unit: "TL" },
              { row: 460, label: "34NGE928 - ELEKTROMEKANİK", unit: "TL" },
              { row: 461, label: "34GAU700- HALİL OMAY", unit: "TL" },
              { row: 465, label: "(GİŞE OPERASYONLARI ŞEFİ) FORD COURİER", unit: "TL" },
              { row: 466, label: "İDARİ İŞLER (NOW PLAZAYA GİDEN ARAÇ YERİNE)", unit: "TL" },
              { row: 467, label: "(ISG) FORD COURİER", unit: "TL" },
            ],
          },
          {
            code: "now", row: 428, label: "NOW Plaza", virtual: true,
            itemRows: [
              { row: 433, label: "34NHN644", unit: "TL" },
              { row: 462, label: "İSMAİL YİĞİT-34NOG217", unit: "TL" },
              { row: 463, label: "HALİM ÖZGÜN ALEMDAR-34PEE298", unit: "TL" },
              { row: 464, label: "HAVUZ ARACI-34MRZ308", unit: "TL" },
            ],
          },
          {
            code: "ic", row: 428, label: "Diğer / İçtaş", virtual: true,
            itemRows: [
              { row: 453, label: "***-34 HRL 696", unit: "TL" },
              { row: 454, label: "HOLDİNG-34 YSS 79", unit: "TL" },
              { row: 456, label: "34MTC538 NEZEHAT ÇEÇEN", unit: "TL" },
              { row: 458, label: "34MBK196 ZAFER HAVALİMANI", unit: "TL" },
              { row: 468, label: "ZAFER HAVALİMANI-NUH332", unit: "TL" },
            ],
          },
        ],
        params: [],
      },
      arac_kira: {
        total: { row: 470, label: "Araç Kira Giderleri", unit: "TL Karşılığı" },
        depts: [
          {
            code: "ana", row: 470, label: "Ana", virtual: true,
            itemRows: [
              { row: 471, label: "KÖPRÜ BAKIM -34 ETA 214", unit: "TL" },
              { row: 472, label: "34 MRS 610", unit: "TL" },
              { row: 473, label: "KÖPRÜ KORUMA ŞUBESİ-34 GST 148", unit: "TL" },
              { row: 474, label: "ODAYERİ BAKIM İŞLETME ŞEFLİĞİ-34 GSS 602", unit: "TL" },
              { row: 476, label: "HÜSEYİNLİ BAKIM İŞLETME ŞEFLİĞİ-34 GSR 992", unit: "TL" },
              { row: 477, label: "34 NHN 664", unit: "TL" },
              { row: 478, label: "İDARİ İŞLER-34 EVP 212", unit: "TL" },
              { row: 479, label: "HÜSEYİNLİ BAKIM İŞLETME ŞEFLİĞİ-34 KJA 117", unit: "TL" },
              { row: 480, label: "ELEKTROMEKANİK-34 KIZ 814", unit: "TL" },
              { row: 481, label: "ELEKTROMEKANİK-34 KIZ 367", unit: "TL" },
              { row: 482, label: "MAKİNE-ATÖLYE-34 KJA 490", unit: "TL" },
              { row: 483, label: "OPERASYON DİREKTÖRÜ-34 KMC 892", unit: "TL" },
              { row: 484, label: "OPERASYON DİREKTÖRÜ-34 NNV 750", unit: "TL" },
              { row: 485, label: "İSG-34 KKR 726", unit: "TL" },
              { row: 486, label: "AMBAR-34 KKR 711", unit: "TL" },
              { row: 487, label: "TESİS BAKIM-34 KKR 610", unit: "TL" },
              { row: 488, label: "PEYZAJ-34 KKR 567", unit: "TL" },
              { row: 489, label: "ODAYERİ BAKIM-34 KKR 640", unit: "TL" },
              { row: 490, label: "İDARİ İŞLER-34 KKR 747", unit: "TL" },
              { row: 491, label: "OTOYOL BAKIM KIDEMLİ MÜDÜRÜ-34 KNR 265", unit: "TL" },
              { row: 492, label: "GİŞE OPERASYONLARI VE İDARİ İŞLER KIDEMLİ  MÜDÜRÜ-34 KNR 306", unit: "TL" },
              { row: 493, label: "YÖNETİM SİSTEMLERİ VE RİSK YÖNETİMİ-34 KTB 406", unit: "TL" },
              { row: 494, label: "ELEKTROMEKANİK-06 EMY 030", unit: "TL" },
              { row: 496, label: "İSG-YENİ TALEP(34 MBR 658)", unit: "TL" },
              { row: 497, label: "34 NFY 640-SCODA FATİH KARAKURT", unit: "TL" },
              { row: 498, label: "34 NGE 928 -E&M SALİH ÜNLÜ", unit: "TL" },
              { row: 499, label: "A-34FOT253 -1 AYLIK ARAÇ", unit: "TL" },
              { row: 500, label: "A-34GAU700 -E&M HALİL OMAY", unit: "TL" },
              { row: 506, label: "KKEG", unit: "TL" },
              { row: 507, label: "(GİŞE OPERASYONLARI ŞEFİ) FORD COURİER", unit: "TL" },
              { row: 508, label: "İDARİ İŞLER (NOW PLAZAYA GİDEN ARAÇ YERİNE)", unit: "TL" },
              { row: 509, label: "(ISG) FORD COURİER", unit: "TL" },
            ],
          },
          {
            code: "now", row: 470, label: "NOW Plaza", virtual: true,
            itemRows: [
              { row: 475, label: "34 NHN 644", unit: "TL" },
              { row: 501, label: "İSMAİL YİĞİT-34NOG217", unit: "TL" },
              { row: 502, label: "HALİM ÖZGÜN ALEMDAR-34PEE298", unit: "TL" },
              { row: 503, label: "34 MRZ 308 ABDULLAH AÇAR", unit: "TL" },
            ],
          },
          {
            code: "ic", row: 470, label: "Diğer / İçtaş", virtual: true,
            itemRows: [
              { row: 495, label: "İDARİ İŞLER-YENİ TALEP(34 MTC 538)", unit: "TL" },
              { row: 504, label: "ZAFER HAVALİMANI (34 MBK 196)", unit: "TL" },
              { row: 505, label: "ZAFER HAVALİMANI (34 NUH 332)", unit: "TL" },
            ],
          },
        ],
        params: [],
      },
      temizlik: {
        total: { row: 513, label: "Temizlik Taşeron Giderleri", unit: "TL Karşılığı" },
        depts: [
          {
            code: "default", row: 518, label: "Temizlik Taşeron", virtual: true,
            itemRows: [
              { row: 519, label: "Gişeler Temizlik", unit: "TL" },
              { row: 520, label: "Mobil Ekip Temizlik", unit: "TL" },
            ],
          },
        ],
        params: [
          { code: "ucret",        row: 514, label: "Ücret",                    unit: "TL" },
          { code: "kisi_toplam",  row: 515, label: "Toplam Kişi Sayısı",       unit: "Kişi" },
          { code: "kisi_giseler", row: 516, label: "Gişeler Temizlik Kişi",    unit: "Kişi" },
          { code: "kisi_mobil",   row: 517, label: "Mobil Ekip Kişi",          unit: "Kişi" },
        ],
      },
      diger_cesitli: {
        total: { row: 525, label: "Diğer Çeşitli Giderler", unit: "TL Karşılığı" },
        depts: [
          {
            code: "temizlik_malzeme", row: 525, label: "Temizlik Malzemesi Giderleri", virtual: true,
            itemRows: [
              { row: 527, label: "ÇÖP POŞETİ SİYAH 80*110 JUMBO", unit: "TL" },
              { row: 530, label: "CİF KREM TEMİZLEYİCİ", unit: "TL" },
              { row: 533, label: "ISLAK MENDİL 72'Lİ", unit: "TL" },
              { row: 536, label: "TUVALET TEMİZLEYİCİ BREF 3'LÜ", unit: "TL" },
              { row: 539, label: "TUVALET KAĞIDI 27'Lİ TORK", unit: "TL" },
              { row: 542, label: "KÖPÜK SABUN 1000 ML.TORK", unit: "TL" },
              { row: 545, label: "FOTOSELLİ KAĞIT HAVLU 21 CM", unit: "TL" },
              { row: 548, label: "LAVABO KOKU GİDERİCİ", unit: "TL" },
              { row: 551, label: "FAİRY BULAŞIK SIVI DETERJANI 10 LT", unit: "TL" },
              { row: 554, label: "FAİRY BULAŞIK PARLATICI 10 LT", unit: "TL" },
              { row: 557, label: "KLOZET KAPAK ÖRTÜSÜ 250'Lİ", unit: "TL" },
              { row: 560, label: "BULAŞIK DETERJANI FİNİSH 90 ADT.", unit: "TL" },
              { row: 563, label: "PRİL BULAŞIK DETERJANI", unit: "TL" },
              { row: 566, label: "SIVI SABUN 5 LT", unit: "TL" },
              { row: 569, label: "MASA ÜSTÜ PEÇETE", unit: "TL" },
              { row: 572, label: "DİĞER TEMİZLİK MALZEMELERİ GİDERİ", unit: "TL" },
            ],
          },
          {
            code: "cay_ocagi", row: 575, label: "Çay Ocağı Giderleri", virtual: true,
            itemRows: [
              { row: 576, label: "AMBALAJLI ŞEKER 5 KG", unit: "TL" },
              { row: 579, label: "DİĞER ÇAY OCAĞI MALZEMELERİ", unit: "TL" },
              { row: 582, label: "ÇAYKUR RİZE TURİST ÇAY 1000 GR", unit: "TL" },
              { row: 585, label: "DOĞADAN  BİTKİ ÇAYI NANE-LİMION 20'Lİ", unit: "TL" },
              { row: 588, label: "DOĞADAN BALLI ZENCEFİL 20'Lİ", unit: "TL" },
              { row: 591, label: "DOĞADAN BİTKİ ADA ÇAYI", unit: "TL" },
              { row: 594, label: "DOĞADAN BİTKİ ÇAYI IHLAMUR 20Lİ PAKET", unit: "TL" },
              { row: 597, label: "DOĞADAN KUŞBURNU 20'Lİ", unit: "TL" },
              { row: 600, label: "DOĞADAN PAPATYA ÇAYI 20'Lİ", unit: "TL" },
              { row: 603, label: "DOĞADAN YEŞİL ÇAY 20'Lİ", unit: "TL" },
              { row: 606, label: "KARTON BARDAK 100'LÜ 30 PAKET", unit: "TL" },
              { row: 609, label: "MEHMET EFENDİ COLOMBİA", unit: "TL" },
              { row: 612, label: "NECAFE GOLD 200GR NESTLE", unit: "TL" },
              { row: 615, label: "PINAR/SÜTAŞ SÜT 1 LT", unit: "TL" },
              { row: 618, label: "SALLAMA ÇAY 100'LÜ", unit: "TL" },
              { row: 621, label: "SÜT TOZU 500 GR", unit: "TL" },
              { row: 624, label: "TAHTA KARIŞTIRICI 100'Lİ", unit: "TL" },
              { row: 627, label: "TOMURCUK ÇAY 200 GR", unit: "TL" },
              { row: 630, label: "TÜRK KAHVESİ /MEHMET EFENDİ 500 GR", unit: "TL" },
            ],
          },
          {
            code: "cep_telefonu", row: 633, label: "Cep Telefonu Giderleri",
            itemRows: [
              { row: 634, label: "CEP TELEFONU GİDERLERİ", unit: "TL" },
            ],
          },
          {
            code: "posta_kargo", row: 635, label: "Posta ve Kargo Giderleri",
            itemRows: [
              { row: 636, label: "POSTA VE KARGO GİDERLERİ", unit: "TL" },
            ],
          },
          {
            code: "kirtasiye", row: 637, label: "Kırtasiye Giderleri",
            itemRows: [
              { row: 638, label: "KIRTASİYE GİDERLERİ", unit: "TL" },
            ],
          },
          {
            code: "sehirici_ulasim", row: 639, label: "Şehiriçi Ulaşım, Otopark",
            itemRows: [
              { row: 640, label: "ŞEHİRİÇİ ULAŞIM,OTOPARK", unit: "TL" },
            ],
          },
          {
            code: "kucuk_demirbas", row: 641, label: "Gider Yazılan Küçük Demirbaşlar",
            itemRows: [
              { row: 642, label: "GİDER YAZILAN KÜÇÜK DEMİRBAŞLAR", unit: "TL" },
            ],
          },
          {
            code: "diger_kamu", row: 643, label: "Diğer Çeşitli Giderler",
            itemRows: [
              { row: 644, label: "DİĞER ÇEŞİTLİ GİDERLER", unit: "TL" },
              { row: 645, label: "DİĞER ÇEŞİTLİ GİDERLER ilaçlama", unit: "TL" },
            ],
          },
        ],
        params: [],
      },
    },
  },
};
